import {responseFailure} from '../src/reasoning-errors.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {routeModel} from '../src/model-routing-policy.js';
import {ModelGateway} from '../src/model-gateway.js';
import {ModelReadinessGate,resetReadinessCache} from '../src/model-readiness.js';
import type {ReviewerModel,BenchmarkDimension} from '../src/reviewer-broker.js';
const now=()=>new Date().toISOString();
const dims:BenchmarkDimension[]=['coding','reasoning','security','toolUse','longContext'];
function model(id:string,score=.8,free=true,provider:ReviewerModel['provider']='openrouter'):ReviewerModel{return{id,provider,free,coding:0,reasoning:0,security:0,context:100000,healthy:true,observedAt:now(),source:'fixture:catalog',benchmarks:dims.map(d=>({benchmark:'fixture-'+d,dimension:d,score,observedAt:now(),source:'fixture:benchmark'}))}}
function gateway(models:ReviewerModel[],fn:(req:any)=>Promise<any>){const g=new ModelGateway({complete:fn},{list:async()=>models,upsert:async()=>{}} as any);g.availableModels=async()=>models;return g}
const req={criticality:'outcome_critical' as const,task:'review:architecture',system:'Review fixture',prompt:'Fixture only',paidModelConsent:false};
test('B01 default and paid-unconsented preferences select strongest qualified free for every criticality',()=>{for(const criticality of ['mechanical','supporting','outcome_critical'] as const){const xs=[model('paid',.99,false),model('free-low',.7),model('free-best',.9)];const r=routeModel(xs,{criticality,task:'review:architecture',configuredModelId:'paid',paidModelConsent:false});assert.equal(r.model?.id,'free-best');assert.equal(r.requiresConsent,false)}});
test('B02 no paid configuration means free-first even when general paid consent exists',()=>{const r=routeModel([model('paid',.99,false),model('free',.8)],{criticality:'supporting',task:'review',paidModelConsent:true});assert.equal(r.model?.id,'free')});
test('B03 explicit authorized paid preference remains selectable',()=>{assert.equal(routeModel([model('paid',.99,false),model('free')],{criticality:'outcome_critical',task:'review',configuredModelId:'paid',paidModelConsent:true}).model?.id,'paid')});
test('B04 automatic routing rejects missing, stale, future and invalid benchmark evidence',()=>{const valid=model('valid',.5);const bad=[model('missing',1),model('stale',1),model('future',1),model('range',1),model('provenance',1)];bad[0].benchmarks=[];for(const b of bad[1].benchmarks!)b.observedAt='2000-01-01T00:00:00Z';for(const b of bad[2].benchmarks!)b.observedAt='2099-01-01T00:00:00Z';for(const b of bad[3].benchmarks!)b.score=99;for(const b of bad[4].benchmarks!)b.source='';assert.equal(routeModel([...bad,valid],{criticality:'outcome_critical',task:'review'}).model?.id,'valid');assert.equal(routeModel([bad[0]],{criticality:'supporting',task:'review'}).model,null)});
test('B05 model ranking follows task evidence instead of unweighted averages',()=>{const a=model('coder',.1),b=model('security',.1);a.benchmarks!.find(x=>x.dimension==='coding')!.score=1;b.benchmarks!.find(x=>x.dimension==='security')!.score=.95;assert.equal(routeModel([a,b],{criticality:'outcome_critical',task:'SECURITY hardening'}).model?.id,'security')});
test('B06 provider-qualified explicit preference does not select an identically named sibling',()=>{const a=model('same',.9,true,'openrouter'),b=model('same',.8,true,'nvidia');assert.equal(routeModel([a,b],{criticality:'supporting',task:'review',configuredModelId:'nvidia::same'}).model?.provider,'nvidia')});
test('B07 gateway falls back for explicit model-specific access restriction',async()=>{const calls:string[]=[];const g=gateway([model('restricted',.9),model('eligible',.8)],async r=>{calls.push(r.model);if(r.model.endsWith('restricted'))throw responseFailure('openrouter','restricted',403,{message:'This model is restricted to agentic harnesses.'},null);return{provider:'openrouter',model:'eligible',text:'reviewed'}});const out=await g.complete(req);assert.equal(out.model,'eligible');assert.deepEqual(calls,['openrouter::restricted','openrouter::eligible'])});
test('B08 generic permission and moderation denial must not trigger model rotation',async()=>{for(const message of ['openrouter 403: Forbidden','openrouter 403: content policy violation; model unavailable','openrouter 401: invalid API key']){const calls:string[]=[];const g=gateway([model('a',.9),model('b')],async r=>{calls.push(r.model);throw new Error(message)});await assert.rejects(()=>g.complete(req));assert.equal(calls.length,1,message)}});
test('B09 exhausted qualified candidates never append an unbenchmarked catalogue default',async()=>{const bad=model('unqualified',1);bad.benchmarks=[];bad.coding=bad.reasoning=bad.security=1;const calls:string[]=[];const g=gateway([bad,model('qualified',.8)],async r=>{calls.push(r.model);throw new Error('openrouter 502: model unavailable')});await assert.rejects(()=>g.complete(req));assert.deepEqual(calls,['openrouter::qualified'])});
test('B10 a paid credit failure uses a qualified free fallback and never another paid model',async()=>{const calls:string[]=[];const g=gateway([model('paid',1,false),model('other-paid',.99,false),model('free',.8)],async r=>{calls.push(r.model);if(r.model.endsWith('paid'))throw responseFailure('openrouter','paid',402,{message:'insufficient credits'},null);return{provider:'openrouter',model:'free',text:'ok'}});const out=await g.complete({...req,configuredModelId:'paid',paidModelConsent:true});assert.equal(out.model,'free');assert.deepEqual(calls,['openrouter::paid','openrouter::free'])});
test('B11 empty output cannot be accepted as a successful model review',async()=>{const g=gateway([model('a')],async()=>({provider:'openrouter',model:'a',text:''}));await assert.rejects(()=>g.complete(req))});
test('B12 a readiness fallback cannot attest that the original model is ready',async()=>{resetReadinessCache();const gate=new ModelReadinessGate({complete:async()=>({provider:'openrouter',model:'other',text:'{"ready":true}',routing:{model:{id:'other',provider:'openrouter'}}})} as any);assert.notEqual((await gate.check('requested',false,true)).state,'READY')});
