import test from 'node:test';import assert from 'node:assert/strict';
import {ReviewCouncil} from '../src/council.js';import {ReasoningFailure} from '../src/reasoning-errors.js';
import {ReviewerCatalogStore} from '../src/reviewer-catalog.js';import {db} from '../src/db.js';
const context:any={product:{description:'FS governed review'},mission:{id:'m',goal:'review',root:'fs',cwd:'fixture'},step:{id:'s',title:'review',acceptance:['no ungoverned retry'],attempts:1},candidate:'fixture',truth:{},traceability:{},repositoryContext:{files:['fixture']},evidence:[]};
test('C01 council does not retry or replace a request refused by authorization/policy',async()=>{let calls=0;const provider:any={availableModels:async()=>[],complete:async()=>{calls++;throw new ReasoningFailure('policy_denied','request',false,403)}};await assert.rejects(()=>new ReviewCouncil(provider).run({missionId:'m',goal:'review',candidate:'fixture',evidence:[],context,roles:['security'],maxAttempts:1,timeoutMs:100}));assert.equal(calls,1)});
test('C02 reviewer timeout aborts the request rather than leaving an orphan completion',async()=>{let aborted=0,calls=0;const provider:any={availableModels:async()=>[],complete:async(r:any)=>{calls++;if(calls===1)return new Promise((_resolve,reject)=>{r.signal?.addEventListener('abort',()=>{aborted++;reject(r.signal.reason)},{once:true})});return{provider:'fixture',model:'fixture',text:JSON.stringify({verdict:'block',summary:'review timed out',findings:[]})}}};await new ReviewCouncil(provider).run({missionId:'m',goal:'review',candidate:'fixture',evidence:[],context,roles:['security'],maxAttempts:1,timeoutMs:30});assert.equal(aborted,1)});
test('C03 catalogue serializes benchmark arrays as JSONB rather than PostgreSQL arrays',async()=>{const old=process.env.DATABASE_URL;process.env.DATABASE_URL='postgresql://fixture@127.0.0.1:1/fixture';const pool=db(),query=pool.query;let value:unknown;pool.query=(async(_sql:string,values:any[])=>{value=values[7];return{rows:[],rowCount:1}}) as any;const benchmarks=[{benchmark:'x',dimension:'coding',score:.8,observedAt:new Date().toISOString(),source:'fixture'}];try{await new ReviewerCatalogStore().upsert([{id:'x',provider:'openrouter',free:true,healthy:true,coding:0,reasoning:0,security:0,context:1000,source:'fixture',observedAt:new Date().toISOString(),benchmarks}] as any);assert.equal(typeof value,'string');assert.deepEqual(JSON.parse(value as string),benchmarks)}finally{pool.query=query;await pool.end();if(old===undefined)delete process.env.DATABASE_URL;else process.env.DATABASE_URL=old}});

test('C04 malformed required reviewer output cannot be overridden into approval',async()=>{let n=0;const provider:any={availableModels:async()=>[],complete:async()=>({model:'fixture',text:++n===1?'not valid review JSON':JSON.stringify({verdict:'approve',summary:'ignored malformed seat',findings:[]})})};const out=await new ReviewCouncil(provider).run({missionId:'m',goal:'review',candidate:'fixture',evidence:[],context,roles:['security'],maxAttempts:1,timeoutMs:100});assert.notEqual(out.adjudication.verdict,'approve');assert.ok(out.failedDimensions.length>0)});
test('C05 each blind reviewer receives only its bounded source chunk',async()=>{const candidate='a'.repeat(45000)+'\n'+'b'.repeat(15000);const lengths:number[]=[];const provider:any={availableModels:async()=>[],complete:async(r:any)=>{const p=JSON.parse(r.prompt);if(p.chunk){lengths.push(p.context.sharedContext.candidate.length);assert.equal(p.context.sharedContext.candidate,p.chunk.candidate)}return{model:'fixture',text:JSON.stringify({verdict:'approve',summary:'structured fixture',findings:[]})}}};const out=await new ReviewCouncil(provider).run({missionId:'m',goal:'review',candidate,evidence:[],context:{...context,candidate},roles:['security'],maxAttempts:1,timeoutMs:100});assert.equal(out.failedDimensions.length,0);assert.ok(lengths.length>=2);assert.ok(lengths.every(n=>n<44000))});
