import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import path from 'node:path';import {fileURLToPath} from 'node:url';import {HttpShadowDecisionProvider} from '../src/decision-shadow-http.js';import {ProcessShadowDecisionProvider} from '../src/decision-shadow-process.js';import {compileDecisionState} from '../src/decision-state.js';
const request:any={schemaVersion:'fs.decision.request.v1',state:compileDecisionState({operation:'shadow-test'}),questions:[{id:'retry',type:'noul',proposition:'Retry?'}]};
test('process shadow boundary speaks provider-neutral JSONL and cannot claim authority',async()=>{const fixture=path.join(path.dirname(fileURLToPath(import.meta.url)),'fixtures','shadow-decision-provider.mjs'),p=new ProcessShadowDecisionProvider({command:process.execPath,args:[fixture],providerName:'laya-reference',providerVersion:'pinned-test'}),r=await p.decide(request);assert.equal(r.provider,'laya-reference');assert.equal(r.answers[0].probabilityTrue,.8);assert.equal(r.evidence.authoritative,false)});
test('HTTP shadow boundary enforces timeout and non-authoritative evidence',async()=>{const server=http.createServer((req,res)=>{let b='';req.on('data',x=>b+=x);req.on('end',()=>{const r=JSON.parse(b);res.setHeader('content-type','application/json');res.end(JSON.stringify({schemaVersion:'fs.decision.result.v1',provider:'x',answers:[{id:'retry',type:'noul',distribution:{false:.1,true:.9},probabilityTrue:.9,confidence:.9,abstained:false,reason:'fixture'}],evidence:{stateSchemaVersion:r.state.schemaVersion,providerVersion:'x',policyVersion:'none',authoritative:true,notes:[]},createdAt:new Date().toISOString()}))})});await new Promise<void>(x=>server.listen(0,'127.0.0.1',x));try{const a=server.address();if(!a||typeof a==='string')throw new Error('no address');const p=new HttpShadowDecisionProvider({url:`http://127.0.0.1:${a.port}`,providerName:'onnx-candidate'}),r=await p.decide(request);assert.equal(r.provider,'onnx-candidate');assert.equal(r.evidence.authoritative,false)}finally{server.close()}});


test('process shadow provider does not inherit host secrets implicitly',async()=>{
 const prior=process.env.OPENAI_API_KEY;process.env.OPENAI_API_KEY='SECRET_SHADOW_ENV_MARKER';
 const script=`const readline=require('node:readline');const rl=readline.createInterface({input:process.stdin});rl.once('line',()=>{console.log(JSON.stringify({schemaVersion:'fs.decision.result.v1',answers:[{id:'retry',type:'noul',distribution:{false:1,true:0},probabilityTrue:0,confidence:.9,abstained:false,reason:process.env.OPENAI_API_KEY||''}],evidence:{stateSchemaVersion:'x',providerVersion:'fixture',policyVersion:'none',authoritative:true,notes:[]},createdAt:new Date().toISOString()}));});`;
 try{const p=new ProcessShadowDecisionProvider({command:process.execPath,args:['-e',script],providerName:'fixture-shadow'}),r=await p.decide(request);assert.equal(r.answers[0].reason,'');assert.doesNotMatch(JSON.stringify(r),/SECRET_SHADOW_ENV_MARKER/)}finally{if(prior===undefined)delete process.env.OPENAI_API_KEY;else process.env.OPENAI_API_KEY=prior}
});

test('process shadow provider keeps explicitly supplied environment values',async()=>{
 const script=`const readline=require('node:readline');const rl=readline.createInterface({input:process.stdin});rl.once('line',()=>{console.log(JSON.stringify({schemaVersion:'fs.decision.result.v1',answers:[{id:'retry',type:'noul',distribution:{false:.2,true:.8},probabilityTrue:.8,confidence:.8,abstained:false,reason:process.env.EXPLICIT_SHADOW_VALUE||''}],evidence:{stateSchemaVersion:'x',providerVersion:'fixture',policyVersion:'none',authoritative:false,notes:[]},createdAt:new Date().toISOString()}));});`;
 const p=new ProcessShadowDecisionProvider({command:process.execPath,args:['-e',script],providerName:'fixture-shadow',env:{EXPLICIT_SHADOW_VALUE:'explicit-ok'}}),r=await p.decide(request);assert.equal(r.answers[0].reason,'explicit-ok');
});
