import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {MissionManager} from '../src/missions.js';
async function manager(){const d=await fs.mkdtemp(path.join(os.tmpdir(),'fs-mission-'));return new MissionManager(d)}
test('mission persists and advances through verification',async()=>{const m=await manager();const x=await m.create({goal:'ship feature',root:'fs',cwd:'.',steps:[{title:'implement',acceptance:['tests pass']},{title:'deploy',requiresApproval:true}]});await m.start(x.id);let n=await m.next(x.id);assert.equal(n.step?.status,'running');let v=await m.verify(x.id,'step-1',true,'tests passed');assert.equal(v.steps[0].status,'completed');n=await m.next(x.id);assert.equal(n.mission.status,'awaiting_approval');await m.approve(x.id,'step-2',true);v=await m.verify(x.id,'step-2',true,'healthy');assert.equal(v.status,'completed');});
test('failed verification remediates then fails closed at attempt limit',async()=>{const m=await manager();const x=await m.create({goal:'fix',root:'fs',cwd:'.',steps:[{title:'fix'}],maxRemediationAttempts:2});await m.start(x.id);await m.next(x.id);let v=await m.verify(x.id,'step-1',false,'test failed');assert.equal(v.steps[0].status,'pending');await m.next(x.id);v=await m.verify(x.id,'step-1',false,'still failed');assert.equal(v.status,'failed');});
test('blocked mission can resume from durable state',async()=>{const m=await manager();const x=await m.create({goal:'work',root:'fs',cwd:'.',steps:[{title:'one'}]});await m.start(x.id);await m.next(x.id);await m.block(x.id,'dependency unavailable');const r=await m.resume(x.id);assert.equal(r.status,'running');assert.equal(r.steps[0].status,'pending');});
test('evidence is durable and summarized separately from mission state',async()=>{const m=await manager();const x=await m.create({goal:'verify',root:'fs',cwd:'.',steps:[{title:'test'}]});await m.addEvidence({missionId:x.id,stepId:'step-1',kind:'test',source:'npm test',status:'pass',summary:'78 tests passed'});await m.addEvidence({missionId:x.id,kind:'repository',source:'git',status:'info',summary:'clean branch'});const s=await m.summary(x.id);assert.equal(s.counts.evidence,2);assert.equal(s.counts.passedEvidence,1);});
test('approval gate cannot be bypassed by next',async()=>{const m=await manager();const x=await m.create({goal:'prod deploy',root:'fs',cwd:'.',steps:[{title:'deploy production',requiresApproval:true}]});await m.start(x.id);await m.next(x.id);await assert.rejects(()=>m.next(x.id),/awaiting approval/);});

test('user interruption pauses a mission and resume clears interruption metadata',async()=>{const base=await fs.mkdtemp(path.join(os.tmpdir(),'fs-mission-')),m=new MissionManager(base);const x=await m.create({goal:'continuous build',root:'fs',cwd:'.',steps:[{title:'work'}]});await m.start(x.id);const paused=await m.interrupt(x.id,'user asked a question');assert.equal(paused.status,'blocked');assert.equal((paused.metadata as any).userInterrupted,true);const resumed=await m.resume(x.id);assert.equal(resumed.status,'running');assert.equal((resumed.metadata as any).userInterrupted,false)});
