import {responseFailure} from '../src/reasoning-errors.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {classifyFailure,reasoningFailure,retryAfterMs} from '../src/reasoning-errors.js';
import * as reasoning from '../src/reasoning.js';
import {ProviderHealthRegistry} from '../src/provider-health.js';
import {ModelGateway} from '../src/model-gateway.js';
const req=(model:string)=>({model,system:'fixture',prompt:'fixture'});
const good=()=>new Response(JSON.stringify({choices:[{message:{content:'ok'},finish_reason:'stop'}]}),{status:200});
const bad=(status:number,message:string)=>new Response(JSON.stringify({error:{code:status,message}}),{status});
async function mocked(fn:any,run:()=>Promise<void>){const old=globalThis.fetch;reasoning.resetReasoningHealth();globalThis.fetch=fn;try{await run()}finally{globalThis.fetch=old;reasoning.resetReasoningHealth()}}
test('R01 explicit provider outage is not model-local and client errors remain fatal',()=>{for(const [status,type]of [[502,''],[503,'provider_unavailable']] as const)assert.equal(classifyFailure(status,'unavailable',type).scope,'provider');for(const status of [400,422])assert.equal(classifyFailure(status,'temporarily unavailable').fallbackAllowed,false)});
test('R02 rate-limit wording refused is not itself a moderation refusal',()=>{assert.equal(classifyFailure(429,'request refused due to upstream rate limit').kind,'rate_limited');assert.equal(classifyFailure(429,'rate limit','content_policy_violation').fallbackAllowed,false)});
test('R03 arbitrary embedded status text is not authoritative transport metadata',()=>{assert.equal(reasoningFailure(new Error('parser fixture has status 429 in its input')).fallbackAllowed,false);assert.equal(reasoningFailure(Object.assign(new Error('rate limited'),{status:429})).kind,'rate_limited');assert.equal(reasoningFailure(new Error('openrouter 429: rate limit')).fallbackAllowed,false)});
test('R04 paid credit cooldown does not block a catalog-free model lacking a free suffix',async()=>{const now=new Date().toISOString(),models:any[]=['paid','free-without-suffix'].map((id,i)=>({id,provider:'openrouter',free:i===1,healthy:true,observedAt:now,source:'fixture',coding:.8,reasoning:.8,security:.8,context:10000,benchmarks:['coding','reasoning','security'].map(d=>({dimension:d,benchmark:d,score:.8,source:'fixture',observedAt:now}))}));const calls:string[]=[];await mocked(async(_u:any,o:any)=>{const m=JSON.parse(o.body).model;calls.push(m);return m==='paid'?bad(402,'insufficient credits'):good()},async()=>{const transport=new reasoning.OpenRouterProvider('fixture');const g=new ModelGateway({complete:r=>transport.complete({...r,model:String(r.model).replace(/^openrouter::/,'')})},{list:async()=>models,upsert:async()=>{}} as any);const out=await g.complete({criticality:'outcome_critical',task:'review:correctness',configuredModelId:'paid',paidModelConsent:true,system:'fixture',prompt:'fixture'});assert.equal(out.text,'ok');assert.deepEqual(calls,['paid','free-without-suffix'])})});
test('R05 only one half-open provider probe is admitted at a time',()=>{const p:any=new ProviderHealthRegistry(1,0);p.failure('fixture');assert.equal(typeof p.acquire,'function');assert.equal(p.acquire('fixture'),true);assert.equal(p.acquire('fixture'),false);p.success('fixture');p.release('fixture');assert.equal(p.acquire('fixture'),true)});
test('R06 invalid numeric retry duration fails closed rather than overflowing expiry',()=>{assert.throws(()=>retryAfterMs('1e308'),/retry|duration/i);assert.equal(retryAfterMs('120'),120000);assert.ok(retryAfterMs('999999999999')>120000,'never shorten a valid server cooldown merely for convenience')});
test('R07 long-lived cooldown bookkeeping is bounded without evicting active rate limits',async()=>{let calls=0;await mocked(async()=>{calls++;return bad(403,'This model is restricted to agentic harnesses.')},async()=>{const p=new reasoning.OpenRouterProvider('fixture');for(let i=0;i<4100;i++)await assert.rejects(()=>p.complete(req('m'+i)));const stats=(reasoning as any).reasoningTransportStats?.();assert.ok(stats&&stats.cooldownEntries<=4096);const before=calls;await assert.rejects(()=>p.complete(req('m0')));assert.equal(calls,before,'an existing active cooldown must not be evicted to admit a new model')})});
test('R08 repeated local transport timeouts contribute to outage detection but caller cancellation does not',async()=>{let calls=0;await mocked(async(_u:any,o:any)=>{calls++;return new Promise((_r,reject)=>{const timer=setTimeout(()=>reject(new Error('fixture late timeout')),500);o.signal.addEventListener('abort',()=>{clearTimeout(timer);reject(o.signal.reason)},{once:true})})},async()=>{const p=new reasoning.OpenRouterProvider('fixture');for(let i=0;i<3;i++)await assert.rejects(()=>p.complete({...req('slow'+i),timeoutMs:5}));assert.ok(reasoning.providerHealth().some(h=>h.state==='open'));await assert.rejects(()=>p.complete({...req('other'),timeoutMs:5}));assert.equal(calls,3)})});
test('R09 account permission denial cannot be converted by generic model availability wording',()=>{assert.equal(classifyFailure(403,'Model X is not available to your API account tier').fallbackAllowed,false);assert.equal(classifyFailure(403,'This model is restricted to agentic harnesses.').scope,'model')});

test('R20 zero-price OpenRouter requests enforce a provider price ceiling, not only cached catalogue pricing',async()=>{await mocked(async(_u:any,o:any)=>{const body=JSON.parse(o.body);assert.deepEqual(body.provider.max_price,{prompt:0,completion:0,request:0,image:0});return good()},async()=>{await new reasoning.OpenRouterProvider('fixture').complete({...req('free-alias'),costClass:'free'})})});

test('R21 hidden account-tier denials remain terminal regardless of a404 transport code',()=>{for(const message of ['Model is not available for your account tier','Model not found for this subscription'])assert.equal(responseFailure('openrouter','fixture',404,{message},null).fallbackAllowed,false);assert.equal(responseFailure('openrouter','fixture',404,{message:'Model does not exist'},null).scope,'model')});

test('R22 numeric retry metadata retains the longest valid cooldown',()=>{const e=responseFailure('openrouter','fixture',429,{message:'limited',metadata:{headers:{'Retry-After':120,'retry-after':'30'}}},'60');assert.equal(e.retryAfterMs,120000)});
test('R23 structured provider-adapter errors preserve authoritative model scope and retry metadata',()=>{const e=reasoningFailure(Object.assign(new Error('Provider returned error'),{status:429,provider:'openrouter',model:'fixture',metadata:{scope:'model',provider_name:'fixture',raw:'private fixture'},retryAfterMs:120000}));assert.equal(e.scope,'model');assert.equal(e.retryAfterMs,120000);assert.ok(!JSON.stringify(e).includes('private fixture'))});

test('R24 malformed numeric Retry-After values fail closed instead of becoming zero',()=>{for(const value of ['Infinity','NaN','1e309','-1','not a valid date'])assert.throws(()=>retryAfterMs(value),/invalid_retry_duration/)});
test('R25 malformed structured retry duration cannot be silently dropped',()=>{for(const value of [-1,Infinity,NaN,1e309,'invalid'])assert.throws(()=>responseFailure('openrouter','fixture',429,{metadata:{retry_after_seconds:value}},null),/invalid_retry_duration/)});
