import {ReasoningFailure} from '../src/reasoning-errors.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {ReviewCouncil} from '../src/council.js';
import {dedupeFindings} from '../src/finding-verification.js';
import {sealCandidate,requiresFreshBlindCouncil} from '../src/council-seal.js';
const context:any={product:{description:'FS review fixture'},mission:{id:'m',goal:'review',root:'fs',cwd:'fixture'},step:{id:'s',title:'review',acceptance:['fail closed'],attempts:1},candidate:'fixture',truth:{},traceability:{},repositoryContext:{files:['fixture']},evidence:[]};
const model=(id:string,free=true):any=>({id,provider:'openrouter',healthy:true,free,coding:.8,reasoning:.8,security:.8,context:100000,source:'fixture',observedAt:new Date().toISOString(),benchmarks:['coding','reasoning','security'].map(d=>({dimension:d,benchmark:d,score:.8,source:'fixture',observedAt:new Date().toISOString()}))});
const answer=(x:any)=>({provider:'openrouter',model:'fixture',text:JSON.stringify(x)});
const approve=()=>answer({verdict:'approve',summary:'fixture',findings:[]});
const run=(provider:any,options:any={})=>new ReviewCouncil(provider).run({missionId:'m',goal:'review',candidate:'fixture',evidence:[],context,roles:['security'],maxAttempts:1,timeoutMs:200,...options});
test('Q01 duplicate reviewer ids in different chunks cannot share one rejected status',async()=>{const candidate='A'.repeat(43000)+'B'.repeat(1000);const out=await run({availableModels:async()=>[],complete:async(r:any)=>{const p=JSON.parse(r.prompt);if(p.chunk)return answer({verdict:'changes',summary:'fixture findings',findings:[{id:'duplicate',severity:'low',location:p.chunk.id+'.ts:1',claim:p.chunk.id==='chunk-1'?'wrong owner':'wrong retry'}]});return answer({verdict:'approve',summary:'rejected first only',findings:[{id:p.findings[0].id,status:'REJECTED',reason:'first only'}]})}},{candidate,context:{...context,candidate}});assert.equal(out.findings.length,2);assert.equal(new Set(out.findings.map((f:any)=>f.id)).size,2);assert.notEqual(out.adjudication.verdict,'approve')});
test('Q02 unrelated defects at the same location do not disappear in fuzzy deduplication',()=>{const a:any={id:'a',role:'security',severity:'high',location:'a.ts:1',claim:'auth bypass in login',evidence:'owner absent'},b:any={...a,id:'b',claim:'timeout in login handler',evidence:'await never settles'};assert.equal(dedupeFindings([a,b]).length,2);assert.equal(dedupeFindings([a,{...a,id:'same-copy'}]).length,2);assert.equal(dedupeFindings([a,{...a}]).length,1)});
test('Q03 retries occur before one blind replacement and each attempt records its chunk',async()=>{const calls:string[]=[];const out=await run({availableModels:async()=>[model('primary'),model('backup')],complete:async(r:any)=>{if(r.task==='review:adjudication')return approve();calls.push(r.configuredModelId);if(calls.length===1)throw new Error('transient');return approve()}},{models:['primary'],maxAttempts:2});assert.deepEqual(calls,['primary','primary']);assert.ok(out.attempts.every(a=>!!(a as any).chunkId))});
test('Q04 paid replacement uses explicit consent after excluding its failed predecessor',async()=>{const calls:string[]=[];const out=await run({availableModels:async()=>[model('failed',false),model('paid-backup',false)],complete:async(r:any)=>{if(r.task==='review:adjudication')return approve();calls.push(r.configuredModelId);if(String(r.configuredModelId).includes('failed'))throw new Error('transient');assert.equal(r.paidModelConsent,true);return approve()}},{models:['openrouter::failed'],paidModelConsent:true});assert.equal(out.failedDimensions.length,0);assert.equal(calls[1],'openrouter::paid-backup')});
test('Q05 changed evidence context invalidates a candidate-only-equal seal',()=>{const original={evidence:'old'},seal=sealCandidate('same',original);assert.equal((requiresFreshBlindCouncil as any)(seal,'same',original),false);assert.equal((requiresFreshBlindCouncil as any)(seal,'same',{evidence:'new'}),true);assert.equal(requiresFreshBlindCouncil(seal,'same'),true)});
test('Q06 contradictory duplicate adjudication ids cannot be last-write-wins approval',async()=>{const out=await run({availableModels:async()=>[],complete:async(r:any)=>{const p=JSON.parse(r.prompt);if(p.chunk)return answer({verdict:'changes',summary:'fixture',findings:[{id:'one',severity:'low',claim:'one defect'}]});return answer({verdict:'approve',summary:'contradiction',findings:[{id:p.findings[0].id,status:'CONFIRMED',reason:'yes'},{id:p.findings[0].id,status:'REJECTED',reason:'no'}]})}});assert.notEqual(out.adjudication.verdict,'approve')});
test('Q07 ambiguous multiple JSON objects remain rejected instead of selecting an approval object',async()=>{let n=0;const out=await run({availableModels:async()=>[],complete:async()=>++n===1?{provider:'fixture',model:'fixture',text:'{"verdict":"approve","summary":"one","findings":[]} {"verdict":"block"}'}:approve()});assert.notEqual(out.adjudication.verdict,'approve')});
test('Q08 chunk evidence binds the exact transmitted candidate string to a recorded hash',async()=>{const candidate='A'.repeat(44000);const hashes:string[]=[];const out=await run({availableModels:async()=>[],complete:async(r:any)=>{const p=JSON.parse(r.prompt);if(p.chunk){const expected=crypto.createHash('sha256').update(p.chunk.candidate).digest('hex');assert.equal(p.chunk.sha256,expected);hashes.push(expected)}return approve()}},{candidate,context:{...context,candidate}});assert.equal(out.failedDimensions.length,0);assert.equal(hashes.length,2);assert.ok(out.attempts.every(a=>hashes.includes((a as any).chunkHash)))});
test('Q09 known credential-shaped material fails before any external provider receives a packet',async()=>{let calls=0;const candidate='sk-or-v1-'+'a'.repeat(64);await assert.rejects(()=>run({availableModels:async()=>[],complete:async()=>{calls++;return approve()}},{candidate,context:{...context,candidate}}),/sensitive|credential/i);assert.equal(calls,0)});

test('Q10 claims with different code operators are distinct even when words match',()=>{const a:any={id:'a',role:'security',severity:'low',location:'a.ts:1',claim:'count < 0 is invalid',evidence:'range'},b={...a,id:'b',claim:'count > 0 is invalid'};assert.equal(dedupeFindings([a,b]).length,2)});
test('Q11 private rechallenge targets the actual reviewer not its failed configured preference',async()=>{let challenged='';const out=await run({availableModels:async()=>[],complete:async(r:any)=>{const p=JSON.parse(r.prompt);if(p.chunk)return{...answer({verdict:'changes',summary:'fixture',findings:[{id:'f',severity:'high',claim:'fixture defect'}]}),model:'actual-reviewer'};if(r.task==='review:rechallenge'){challenged=r.configuredModelId;return answer({verdict:'RETRACT',reason:'fixture disproved'})}return answer({verdict:'approve',summary:'fixture disproved',findings:[{id:p.findings[0].id,status:'REJECTED',reason:'fixture'}]})}},{models:['configured-preference']});assert.equal(challenged,'openrouter::actual-reviewer');assert.equal(out.adjudication.verdict,'approve')});

test('Q12 replacement cannot claim independence when failed reviewer identity is unresolved',async()=>{let calls=0;const out=await run({availableModels:async()=>[model('actual')],complete:async(r:any)=>{if(r.task==='review:adjudication')return approve();calls++;throw new Error('unidentified provider failure')}},{models:['unresolved-alias']});assert.equal(calls,1);assert.notEqual(out.adjudication.verdict,'approve');assert.ok(out.failedDimensions.length>0)});
test('Q13 unserializable candidate context fails safely before provider dispatch',async()=>{const c:any={...context};c.truth=c;let calls=0;await assert.rejects(()=>run({availableModels:async()=>[],complete:async()=>{calls++;return approve()}},{context:c}),/COUNCIL_INVALID_PAYLOAD/);assert.equal(calls,0)});

test('Q14 adjudication failure preserves completed reviewer evidence in a fail-closed result',async()=>{const out=await run({availableModels:async()=>[],complete:async(r:any)=>{if(r.task==='review:adjudication')throw new Error('provider unavailable');return approve()}});assert.equal(out.adjudication.verdict,'block');assert.equal(out.reviews.length,1);assert.equal(out.attempts.length,1);assert.ok(out.failedDimensions.some((x:string)=>x.includes('adjudication')))});
test('Q15 rechallenge sees the original finding chunk summary rather than aggregated role summaries',async()=>{const candidate='A'.repeat(43000)+'B'.repeat(1000);let challenged=0;const out=await run({availableModels:async()=>[],complete:async(r:any)=>{const p=JSON.parse(r.prompt);if(p.chunk)return answer({verdict:'changes',summary:p.chunk.id+' private summary',findings:[{id:p.chunk.id,severity:'high',claim:'finding '+p.chunk.id}]});if(r.task==='review:rechallenge'){challenged++;assert.equal(p.originalSummary,p.finding.chunkId+' private summary');return answer({verdict:'RETRACT',reason:'fixture withdrawn'})}return answer({verdict:'approve',summary:'fixture rejected',findings:p.findings.map((f:any)=>({id:f.id,status:'REJECTED',reason:'fixture'}))})}},{candidate,context:{...context,candidate}});assert.equal(challenged,2);assert.equal(out.adjudication.verdict,'approve')});
test('Q16 proposed refinement is retained as untrusted evidence rather than overwriting a sealed original claim',async()=>{const out=await run({availableModels:async()=>[],complete:async(r:any)=>{const p=JSON.parse(r.prompt);if(p.chunk)return answer({verdict:'changes',summary:'fixture',findings:[{id:'original',severity:'high',claim:'original claim'}]});if(r.task==='review:rechallenge')return answer({verdict:'REFINE',reason:'refined evidence',refinedFinding:{claim:'proposed refinement'}});if(r.task==='review:dispute-adjudication')return answer({status:'INSUFFICIENT_EVIDENCE',reason:'new claim unverified'});return answer({verdict:'approve',summary:'original disproved',findings:p.findings.map((f:any)=>({id:f.id,status:'REJECTED',reason:'fixture'}))})}});assert.equal(out.rechallenges[0].refinedFinding?.claim,'proposed refinement');assert.equal(out.findings[0].claim,'original claim');assert.equal(out.adjudication.verdict,'block')});

test('Q18 catalogue replacement lookup cannot hang past the review timeout',async()=>{let out:any;const finished=await Promise.race([run({availableModels:async()=>new Promise(()=>{}),complete:async(r:any)=>{if(r.task==='review:adjudication')return answer({verdict:'block',summary:'no reviewer',findings:[]});throw new Error('fixture') }},{timeoutMs:20,models:['primary']}).then(x=>{out=x;return true}),new Promise(r=>setTimeout(()=>r(false),200))]);assert.equal(finished,true);assert.equal(out.adjudication.verdict,'block');assert.ok(out.failedDimensions.length>0)});
test('Q19 arbitrary exception kind values cannot masquerade as safe classification labels',async()=>{const marker='private_customer_classification';const out=await run({availableModels:async()=>[],complete:async(r:any)=>{if(r.task==='review:adjudication')throw new ReasoningFailure(marker,'request',false);return approve()}});assert.ok(!JSON.stringify(out).includes(marker));assert.equal(out.adjudication.verdict,'block')});
