import test from 'node:test';
import assert from 'node:assert/strict';
import * as reasoning from '../src/reasoning.js';
async function mockFetch(fn:any,run:()=>Promise<void>){const old=globalThis.fetch;(reasoning as any).resetReasoningHealth?.();globalThis.fetch=fn;try{await run()}finally{globalThis.fetch=old;(reasoning as any).resetReasoningHealth?.()}}
const req=(model:string)=>({model,system:'fixture',prompt:'fixture'});
const good=()=>new Response(JSON.stringify({choices:[{message:{content:'ok'}}]}),{status:200});
const bad=(status:number,message:string,metadata:any={},headers:any={})=>new Response(JSON.stringify({error:{code:status,message,metadata}}),{status,headers});
test('T01 three model access failures do not open a circuit for an unrelated model',async()=>{let n=0;await mockFetch(async()=>++n<=3?bad(403,'This model is restricted to agentic harnesses.'):good(),async()=>{const p=new reasoning.OpenRouterProvider('fixture-not-a-secret');for(let i=0;i<3;i++)await assert.rejects(()=>p.complete(req('restricted-'+i)));assert.equal((await p.complete(req('allowed'))).text,'ok');assert.equal(n,4)})});
test('T02 provider-wide Retry-After prevents immediate same-provider model rotation',async()=>{let n=0;await mockFetch(async()=>{n++;return bad(429,'Account rate limit exceeded',{}, {'retry-after':'60'})},async()=>{const p=new reasoning.OpenRouterProvider('fixture');await assert.rejects(()=>p.complete(req('one')));await assert.rejects(()=>p.complete(req('two')));assert.equal(n,1)})});
test('T03 model-specific Retry-After blocks only that model, not its provider siblings',async()=>{let n=0;await mockFetch(async(_u:any,o:any)=>{n++;return JSON.parse(o.body).model==='busy'?bad(429,'Model rate limited upstream',{scope:'model',provider_name:'fixture'},{'retry-after':'60'}):good()},async()=>{const p=new reasoning.OpenRouterProvider('fixture');await assert.rejects(()=>p.complete(req('busy')));assert.equal((await p.complete(req('other'))).text,'ok');await assert.rejects(()=>p.complete(req('busy')));assert.equal(n,2)})});
test('T04 embedded error in HTTP 200 is not a successful empty completion',async()=>{await mockFetch(async()=>new Response(JSON.stringify({error:{code:503,message:'provider unavailable'}}),{status:200}),async()=>{await assert.rejects(()=>new reasoning.OpenRouterProvider('fixture').complete(req('one')))})});
test('T05 structured permission refusal outranks misleading availability wording',async()=>{await mockFetch(async()=>bad(403,'Model unavailable',{error_type:'content_policy_violation',flagged_input:'private text'}),async()=>{await assert.rejects(()=>new reasoning.OpenRouterProvider('fixture').complete(req('one')),(e:any)=>{assert.equal(e.fallbackAllowed,false);assert.doesNotMatch(JSON.stringify(e),/private text/);return true})})});
test('T06 requests carry an abort signal and observe caller cancellation',async()=>{await mockFetch(async(_u:any,o:any)=>{assert.ok(o.signal);return new Promise((_res,rej)=>{if(o.signal.aborted)rej(o.signal.reason);else o.signal.addEventListener('abort',()=>rej(o.signal.reason),{once:true})})},async()=>{const c=new AbortController();const p=new reasoning.OpenRouterProvider('fixture').complete({...req('one'),signal:c.signal} as any);c.abort(new Error('caller cancelled'));await assert.rejects(()=>p)})});
test('T07 empty successful HTTP responses remain explicit failures',async()=>{await mockFetch(async()=>new Response(JSON.stringify({choices:[{message:{content:''},finish_reason:'length'}]}),{status:200}),async()=>{await assert.rejects(()=>new reasoning.OpenRouterProvider('fixture').complete(req('one')))})});

test('T08 non-JSON authorization error retains a fatal boundary',async()=>{await mockFetch(async()=>new Response('Forbidden',{status:403}),async()=>{await assert.rejects(()=>new reasoning.OpenRouterProvider('fixture').complete(req('one')),(e:any)=>{assert.equal(e.fallbackAllowed,false);assert.equal(e.status,403);return true})})});
