import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {ProcessManager} from '../src/processes.js';import {RemoteOperations} from '../src/operations.js';import {validateConfig} from '../src/config.js';
async function ops(){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'fs-plan-'));return new RemoteOperations(validateConfig({endpointSecret:'e'.repeat(48),actionsSecret:'a'.repeat(48),roots:[{name:'work',path:dir}]}),new ProcessManager({shell:'powershell.exe',maxOutputBytes:1024*1024}));}
test('planWork routes mixed product research engineering goals intelligently',async()=>{const o=await ops();const p=await o.planWork('Research competitors and user needs, design the UX, then build and test the product');assert.equal(p.mode,'mixed');assert.ok(p.detectedDomains.includes('research'));assert.ok(p.detectedDomains.includes('product'));assert.ok(p.detectedDomains.includes('design_ux'));assert.ok(p.detectedDomains.includes('engineering'));assert.ok(p.recommendedSkills.includes('deep-research'));assert.ok(p.recommendedSkills.includes('frontend-design-direction'));assert.match(p.productPolicy,/user problem/i);});
test('planWork can be explicitly product focused',async()=>{const o=await ops();const p=await o.planWork('Prioritize onboarding improvements','product');assert.equal(p.mode,'product');assert.ok(p.recommendedSkills.includes('competitive-platform-analysis'));});
test('planWork makes Flutter mobile work first class',async()=>{const o=await ops();const p=await o.planWork('Build a polished offline-first Flutter app for iPhone and Android tablets with accessible responsive UI');assert.equal(p.mode,'mixed');assert.ok(p.detectedDomains.includes('mobile'));assert.ok(p.mobilePlatforms.includes('flutter'));assert.ok(p.mobilePlatforms.includes('ios'));assert.ok(p.mobilePlatforms.includes('android'));for(const s of ['flutter-engineering','dart-flutter-patterns','flutter-dart-code-review','ios-interface-design','android-material-design','mobile-product-design','offline-first-mobile','mobile-release-readiness'])assert.ok(p.recommendedSkills.includes(s),s);});
test('planWork routes React Native independently from Flutter',async()=>{const o=await ops();const p=await o.planWork('Implement the React Native mobile onboarding flow');assert.ok(p.detectedDomains.includes('mobile'));assert.ok(p.mobilePlatforms.includes('react_native'));assert.ok(p.recommendedSkills.includes('react-native-patterns'));assert.ok(p.recommendedSkills.includes('stitch-react-native'));assert.ok(!p.recommendedSkills.includes('flutter-engineering'));});
test('planWork adds curated product and UX lenses for discovery work',async()=>{const o=await ops();const p=await o.planWork('Research customer needs and product retention, then design and test a polished usable onboarding UI');for(const s of ['wondel-jobs-to-be-done','wondel-continuous-discovery','wondel-lean-analytics','wondel-ux-heuristics','wondel-microinteractions'])assert.ok(p.recommendedSkills.includes(s),s);});
test('planWork routes official Android adaptive and testing guidance',async()=>{const o=await ops();const p=await o.planWork('Build an Android Jetpack Compose app for phones tablets and foldables with edge-to-edge UI and tests');for(const s of ['android-official-adaptive','android-official-edge-to-edge','android-official-testing-setup'])assert.ok(p.recommendedSkills.includes(s),s);});
