import type {FastifyInstance,FastifyReply,FastifyRequest} from 'fastify';import {AuthStore,type AuthPrincipal,type WorkspaceRole} from './auth-store.js';
const token=(r:FastifyRequest)=>r.headers.authorization?.startsWith('Bearer ')?r.headers.authorization.slice(7).trim():'';
const role=(p:AuthPrincipal,allowed:WorkspaceRole[])=>{if(!p.role||!allowed.includes(p.role))throw new Error('Forbidden.')};
export function registerAuthRoutes(app:FastifyInstance){const store=new AuthStore();const auth=async(r:FastifyRequest,reply:FastifyReply)=>{const t=token(r),p=t?await store.resolve(t):null;if(!p)return reply.code(401).send({error:'Unauthorized.'});(r as any).principal=p;(r as any).sessionToken=t};
 app.post('/api/auth/signup',async(r:any,reply)=>{try{const b=r.body??{};if(!b.token||!b.username||!b.password||String(b.password).length<12)return reply.code(400).send({error:'Token, username and password (12+ characters) are required.'});return reply.code(201).send(await store.signup(b))}catch(e){return reply.code(400).send({error:e instanceof Error?e.message:'Signup failed.'})}});
 app.post('/api/auth/login',async(r:any,reply)=>{try{return reply.send(await store.login(r.body??{}))}catch{return reply.code(401).send({error:'Invalid username or password.'})}});
 app.post('/api/auth/logout',{preHandler:auth},async(r:any)=>store.logout(r.sessionToken));app.get('/api/auth/me',{preHandler:auth},async(r:any)=>({principal:r.principal}));
 app.get('/api/admin/users',{preHandler:auth},async(r:any,reply)=>{try{role(r.principal,['owner','admin']);return {users:await store.users(r.principal.workspaceId)}}catch(e){return reply.code(403).send({error:'Forbidden.'})}});
 app.post('/api/admin/invitations',{preHandler:auth},async(r:any,reply)=>{try{role(r.principal,['owner','admin']);const b=r.body??{};return reply.code(201).send(await store.invite({workspaceId:r.principal.workspaceId,email:b.email,role:b.role,createdBy:r.principal.userId}))}catch(e){return reply.code(403).send({error:e instanceof Error?e.message:'Forbidden.'})}});
 app.patch('/api/admin/users/:id/role',{preHandler:auth},async(r:any,reply)=>{try{role(r.principal,['owner','admin']);if(r.principal.role!=='owner'&&r.body?.role==='owner')throw new Error('Only owner can grant owner role.');return await store.setRole(r.principal.workspaceId,r.params.id,r.body?.role)}catch(e){return reply.code(403).send({error:e instanceof Error?e.message:'Forbidden.'})}});
 app.patch('/api/admin/users/:id/status',{preHandler:auth},async(r:any,reply)=>{try{role(r.principal,['owner','admin']);return await store.setStatus(r.principal.workspaceId,r.params.id,r.body?.status)}catch(e){return reply.code(403).send({error:e instanceof Error?e.message:'Forbidden.'})}});
 app.post('/api/admin/users/:id/password-reset',{preHandler:auth},async(r:any,reply)=>{try{role(r.principal,['owner','admin']);return await store.resetToken(r.principal.workspaceId,r.params.id,r.principal.userId)}catch(e){return reply.code(403).send({error:e instanceof Error?e.message:'Forbidden.'})}});
 app.post('/api/auth/password-reset',async(r:any,reply)=>{try{if(!r.body?.token||String(r.body?.password??'').length<12)return reply.code(400).send({error:'Token and password (12+ characters) are required.'});return await store.reset(r.body.token,r.body.password)}catch(e){return reply.code(400).send({error:e instanceof Error?e.message:'Reset failed.'})}});
}
