import type {SkillSelection} from './skill-router.js';
export type TruthNeed='repository_state'|'runtime_state'|'current_external_fact'|'official_documentation'|'user_behavior'|'design_state'|'database_state'|'ci_state'|'deployment_state'|'security_state'|'procedure_guidance';
export interface BrokerCandidate{id:string;kind:'mcp'|'tool'|'skill'|'research';authority:number;freshness:number;determinism:number;directness:number;available:boolean;reason:string}
export interface BrokerDecision{need:TruthNeed;selected:BrokerCandidate|null;fallbacks:BrokerCandidate[];policy:string}
const weights={authority:.35,freshness:.25,determinism:.25,directness:.15};
const score=(c:BrokerCandidate)=>c.available?(c.authority*weights.authority+c.freshness*weights.freshness+c.determinism*weights.determinism+c.directness*weights.directness):-1;
export function broker(need:TruthNeed,candidates:BrokerCandidate[]):BrokerDecision{const ranked=[...candidates].sort((a,b)=>score(b)-score(a));return {need,selected:ranked.find(x=>x.available)??null,fallbacks:ranked.filter(x=>x.available).slice(1),policy:'Prefer the most authoritative, fresh, deterministic and direct available source. Skills guide procedure but never outrank direct authoritative evidence for truth claims.'}}
export function defaultCandidates(need:TruthNeed,available:Set<string>):BrokerCandidate[]{const c=(id:string,kind:BrokerCandidate['kind'],a:number,f:number,d:number,x:number,reason:string):BrokerCandidate=>({id,kind,authority:a,freshness:f,determinism:d,directness:x,available:available.has(id),reason});switch(need){case'repository_state':return[c('filesystem','mcp',1,1,1,1,'Direct repository files'),c('git','mcp',1,1,1,1,'Direct Git state')];case'runtime_state':return[c('process','mcp',1,1,1,1,'Direct process state'),c('browser','mcp',.9,1,1,1,'Observed application runtime')];case'database_state':return[c('database','mcp',1,1,1,1,'Direct governed database query')];case'ci_state':return[c('github','mcp',1,1,1,1,'Authoritative repository CI provider')];case'deployment_state':return[c('cloud','mcp',1,1,1,1,'Authoritative deployment provider'),c('browser','mcp',.8,1,1,.8,'Observed deployed application')];case'design_state':return[c('figma','mcp',1,1,1,1,'Authoritative design source'),c('browser','mcp',.7,1,1,.8,'Rendered implementation')];case'user_behavior':return[c('analytics','mcp',1,1,1,1,'Observed user behavior'),c('research','research',.6,1,.4,.5,'External research fallback')];case'official_documentation':return[c('official-docs','research',1,1,.8,1,'First-party current documentation'),c('research','research',.7,1,.5,.7,'Broader current research')];case'current_external_fact':return[c('official-source','research',1,1,.8,1,'Current authoritative primary source'),c('research','research',.7,1,.5,.7,'Corroborated current research')];case'security_state':return[c('security-scanner','tool',.9,1,1,1,'Deterministic security scanner'),c('repository','mcp',.8,1,1,.8,'Direct source inspection')];case'procedure_guidance':return[c('skills','skill',.7,.7,.3,1,'Curated procedural guidance')];}}
export function needsFor(text:string):TruthNeed[]{const t=text.toLowerCase(),n=new Set<TruthNeed>(['repository_state','procedure_guidance']);if(/current|latest|law|legal|regulat|market|competitor|price|policy/.test(t))n.add('current_external_fact');if(/documentation|sdk|api|framework|library/.test(t))n.add('official_documentation');if(/database|sql|migration|schema/.test(t))n.add('database_state');if(/ci|github actions|pipeline|check/.test(t))n.add('ci_state');if(/deploy|production|staging|railway|vercel|cloud/.test(t))n.add('deployment_state');if(/ui|ux|browser|frontend|runtime/.test(t))n.add('runtime_state');if(/figma|design source|design system/.test(t))n.add('design_state');if(/analytics|funnel|retention|conversion|user behavior/.test(t))n.add('user_behavior');if(/security|auth|vulnerab|secret/.test(t))n.add('security_state');return [...n]}
export function skillContext(selection:SkillSelection,maxChars=24000){let used=0;return selection.selected.map(s=>{const header=`SKILL ${s.id}: ${s.description}\nEvaluation: ${s.evaluation.verdict} ${s.evaluation.score}/5\nResources: ${s.resources.join(', ')}`;const text=header.slice(0,Math.max(0,maxChars-used));used+=text.length;return {id:s.id,context:text}}).filter(x=>x.context.length)}