import crypto from 'node:crypto';
import {modelGateway,ModelGateway} from './model-gateway.js';
import {dedupeFindings,blockersNeedSkeptic,reviewCanPass,type Finding} from './finding-verification.js';
import {reviewerContext,type CouncilContext} from './council-context.js';
export interface CouncilReview{role:string;model?:string;verdict:'approve'|'changes'|'block';summary:string;findings:Finding[];raw:string}
const roles=['requirements','security','correctness','testing','hardening','architecture'];
const severity=(x:unknown):Finding['severity']=>['low','medium','high','critical'].includes(String(x))?String(x) as Finding['severity']:'medium';
function parse(role:string,raw:string):CouncilReview{let x:any;try{x=JSON.parse(raw.match(/\{[\s\S]*\}/)?.[0]??raw)}catch{};const verdict=['approve','changes','block'].includes(x?.verdict)?x.verdict:'changes',rawFindings=Array.isArray(x?.findings)?x.findings:[];const findings:Finding[]=rawFindings.map((f:any,i:number)=>typeof f==='string'?{id:`${role}-${i}`,role,severity:verdict==='block'?'high':'medium',claim:f}:{id:String(f?.id??`${role}-${i}`),role,severity:severity(f?.severity),location:f?.location?String(f.location):undefined,claim:String(f?.claim??f?.summary??'Unstructured reviewer finding'),evidence:f?.evidence?String(f.evidence):undefined});return {role,verdict,summary:String(x?.summary??'Reviewer response requires adjudication.'),findings,raw}}
export class ReviewCouncil{constructor(private readonly provider:ModelGateway=modelGateway()){}
 async run(input:{missionId:string;goal:string;candidate:string;evidence:unknown;context?:CouncilContext;roles?:string[];models?:string[];paidModelConsent?:boolean}){const selected=input.roles?.length?input.roles:roles,reviews:CouncilReview[]=[],failedDimensions:string[]=[],shared=input.context??{product:{description:input.goal},mission:{id:input.missionId,goal:input.goal,root:'',cwd:''},step:{id:'unknown',title:'unknown',acceptance:[],attempts:0},candidate:input.candidate,capabilityContract:{},requirements:{overrides:[]},risk:{},truth:{},traceability:{},evidence:Array.isArray(input.evidence)?input.evidence:[]} as CouncilContext;for(let i=0;i<selected.length;i++){const role=selected[i];try{const out=await this.provider.complete({criticality:'outcome_critical',task:'review:'+role,configuredModelId:input.models?.[i],paidModelConsent:!!input.paidModelConsent,system:`You are the independent ${role} specialist in a software engineering review council. You receive the product/service context, exact current engineering task, acceptance criteria, requirements decisions, risk, repository/research/design context when available, traceability, known/unknown state, and objective evidence. Stay within your specialist remit but consider cross-cutting facts that materially affect it. Return JSON {verdict:"approve|changes|block",summary:string,findings:[{severity:"low|medium|high|critical",location?:string,claim:string,evidence?:string}]}. Every material claim must be grounded in supplied context/evidence; explicitly identify missing context rather than inventing it.`,prompt:JSON.stringify(reviewerContext(shared,role))});reviews.push(parse(role,out.text))}catch(error){failedDimensions.push(role);reviews.push({role,verdict:'block',summary:`Reviewer dimension failed: ${error instanceof Error?error.message:String(error)}`,findings:[{id:`${role}-failure`,role,severity:'high',claim:'Required reviewer dimension did not complete.'}],raw:''})}}
 const findings=dedupeFindings(reviews.flatMap(r=>r.findings)),blockers=blockersNeedSkeptic(findings),verified:Finding[]=[];for(const f of blockers){try{const out=await this.provider.complete({criticality:'outcome_critical',task:'review:skeptic',configuredModelId:input.models?.[selected.length],paidModelConsent:!!input.paidModelConsent,system:'You are an independent skeptical verifier. Your job is to falsify a HIGH/CRITICAL finding if the complete supplied factual context and deterministic evidence do not support it. Understand the product, current task and acceptance criteria before judging the finding. Uncertainty does NOT clear a blocker. Return JSON {verdict:"confirmed|rejected|uncertain",reason:string}.',prompt:JSON.stringify({sharedContext:shared,finding:f,originatingReviews:reviews.filter(r=>r.findings.some(x=>x.id===f.id)).map(({raw,...r})=>r)})});let x:any;try{x=JSON.parse(out.text.match(/\{[\s\S]*\}/)?.[0]??out.text)}catch{};const verdict=['confirmed','rejected','uncertain'].includes(x?.verdict)?x.verdict:'uncertain';verified.push({...f,status:verdict})}catch{verified.push({...f,status:'uncertain'})}}
 const merged=findings.map(f=>verified.find(v=>v.id===f.id)??f),failClosed=!reviewCanPass(merged,failedDimensions);const adjudication=await this.provider.complete({criticality:'outcome_critical',task:'review:adjudication',configuredModelId:input.models?.[selected.length+1],paidModelConsent:!!input.paidModelConsent,system:'You are the independent adjudicator of a software engineering review council. First understand the product/service, intended users, mission goal, exact current task, acceptance criteria, requirements decisions/overrides, risk, architecture/repository/research context, known/unknown state and deterministic evidence. Then reconcile specialist reviews and skeptic outcomes. Deterministic observed evidence outranks model opinion. Do not convert missing evidence into facts. HIGH/CRITICAL findings may be cleared only when the independent skeptic rejected them. Uncertain blockers and failed reviewer dimensions fail closed. Return JSON {verdict:"approve|changes|block",summary:string,requiredActions:string[],factualBasis:string[],remainingUncertainty:string[]}.',prompt:JSON.stringify({sharedContext:shared,reviews:reviews.map(({raw,...r})=>r),findings:merged,failedDimensions,failClosed,adjudicationRules:{evidenceHierarchy:['fresh deterministic evidence','explicit requirements and user decisions','repository/research context','reviewer interpretation'],uncertaintyDoesNotEqualApproval:true}})});let decision:any;try{decision=JSON.parse(adjudication.text.match(/\{[\s\S]*\}/)?.[0]??adjudication.text)}catch{decision={verdict:'changes',summary:'Adjudicator output was not structured.',requiredActions:[],factualBasis:[],remainingUncertainty:['Adjudicator response could not be parsed.']}}if(failClosed&&decision.verdict==='approve')decision={...decision,verdict:'block',summary:'Council failed closed because unresolved blockers or reviewer dimensions remain.'};return {id:`council-${Date.now()}-${crypto.randomBytes(3).toString('hex')}`,context:shared,reviews,findings:merged,failedDimensions,adjudication:decision,rawAdjudication:adjudication.text}}
}
