export type DecisionQuestion=ChoiceQuestion|ScoreQuestion|NoulQuestion;
export interface ChoiceQuestion{id:string;type:'choice';options:string[];instructions?:string}
export interface ScoreQuestion{id:string;type:'score';levels:string[];instructions?:string}
export interface NoulQuestion{id:string;type:'noul';proposition:string;instructions?:string}
export interface DecisionRequest{schemaVersion:'fs.decision.request.v1';state:DecisionState;questions:DecisionQuestion[]}
export interface DecisionAnswer{id:string;type:DecisionQuestion['type'];distribution:Record<string,number>;selected?:string;expectedScore?:number;probabilityTrue?:number;confidence:number;abstained:boolean;reason:string}
export interface DecisionResult{schemaVersion:'fs.decision.result.v1';provider:string;answers:DecisionAnswer[];evidence:DecisionEvidence;createdAt:string}
export interface DecisionEvidence{stateSchemaVersion:string;providerVersion:string;policyVersion:string;authoritative:boolean;notes:string[]}
export interface DecisionProvider{name:string;version:string;decide(request:DecisionRequest):Promise<DecisionResult>}
export interface DecisionState{schemaVersion:'fs.decision.state.v1';operation:string;missionPhase?:string;attempt:number;maxAttempts:number;risk:'low'|'medium'|'high'|'critical';destructive:boolean;localOnly:boolean;sensitive:boolean;worker:{localAvailable:boolean;sandboxAvailable:boolean;hostedAvailable:boolean;healthy?:boolean};checks:{test?:CheckState;build?:CheckState;lint?:CheckState;typecheck?:CheckState};evidence:{required:number;freshPassing:number;freshFailing:number;complete:boolean};failure?:{class:'none'|'transient'|'source'|'environment'|'dependency'|'policy'|'unknown';code?:string};models:{freeAvailable:boolean;paidConsent:boolean;councilAvailable:boolean};repository:{dirty:boolean;changedFileCount:number;changedDomains:string[]}}
export type CheckState='unknown'|'pass'|'fail'|'running';
export function validateDecisionRequest(request:DecisionRequest){if(request.schemaVersion!=='fs.decision.request.v1')throw new Error('Unsupported decision request schema.');if(!request.questions.length)throw new Error('At least one decision question is required.');const ids=new Set<string>();for(const q of request.questions){if(!q.id||ids.has(q.id))throw new Error(`Decision question id must be unique: ${q.id}`);ids.add(q.id);if(q.type==='choice'&&(!q.options.length||q.options.length>20))throw new Error('Choice questions require 1-20 options.');if(q.type==='score'&&(!q.levels.length||q.levels.length>20))throw new Error('Score questions require 1-20 ordered levels.');}return request}
