export type GitHubAction='capabilities'|'repository'|'pull_requests'|'pull_request'|'create_pull_request'|'comment'|'checks'|'workflow_runs'|'issues'|'create_issue';
export class GitHubProvider{
 capabilities(){return {provider:'github',transport:'rest',authentication:'environment_variable',tokenEnvDefault:'GITHUB_TOKEN',operations:['repository','pull_requests','pull_request','create_pull_request','comment','checks','workflow_runs','issues','create_issue'],evidenceKinds:['repository','pull_request','ci_check','workflow_run','issue'],configured:this.hasToken('GITHUB_TOKEN')||this.hasToken('GH_TOKEN')};}
 private hasToken(name:string){return !!(process.env[name]||(process.platform==='win32'?undefined:undefined));}
 private token(name='GITHUB_TOKEN'){if(!/^[A-Z][A-Z0-9_]*$/.test(name))throw new Error('tokenEnv must be an uppercase environment variable name.');const v=process.env[name]||process.env.GH_TOKEN;if(!v)throw new Error(`GitHub token environment variable '${name}' is not configured.`);return v}
 private repo(v:string){const m=v.match(/^([A-Za-z0-9_.-]+)\/([A-Za-z0-9_.-]+)$/);if(!m)throw new Error('repository must be owner/name.');return `${m[1]}/${m[2]}`}
 private async api(method:string,url:string,tokenEnv:string,body?:unknown){const r=await fetch(`https://api.github.com${url}`,{method,headers:{Authorization:`Bearer ${this.token(tokenEnv)}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'FS-Remote-v2'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(30000)});const text=await r.text();let data:any=text;try{data=text?JSON.parse(text):null}catch{}if(!r.ok)throw new Error(`GitHub API ${r.status}: ${typeof data==='object'?(data.message??'request failed'):String(data).slice(0,300)}`);return {status:r.status,data,requestId:r.headers.get('x-github-request-id')};}
 async run(action:GitHubAction,input:{repository?:string;number?:number;tokenEnv?:string;title?:string;body?:string;head?:string;base?:string;state?:'open'|'closed'|'all';limit?:number}){if(action==='capabilities')return this.capabilities();if(!input.repository)throw new Error('repository is required.');const repo=this.repo(input.repository),t=input.tokenEnv??'GITHUB_TOKEN',limit=Math.min(Math.max(input.limit??30,1),100);switch(action){case'repository':return this.api('GET',`/repos/${repo}`,t);case'pull_requests':return this.api('GET',`/repos/${repo}/pulls?state=${input.state??'open'}&per_page=${limit}`,t);case'pull_request':if(!input.number)throw new Error('number is required.');return this.api('GET',`/repos/${repo}/pulls/${input.number}`,t);case'create_pull_request':if(!input.title||!input.head||!input.base)throw new Error('title, head and base are required.');return this.api('POST',`/repos/${repo}/pulls`,t,{title:input.title,body:input.body??'',head:input.head,base:input.base});case'comment':if(!input.number||!input.body)throw new Error('number and body are required.');return this.api('POST',`/repos/${repo}/issues/${input.number}/comments`,t,{body:input.body});case'checks':if(!input.head)throw new Error('head commit SHA is required.');return this.api('GET',`/repos/${repo}/commits/${encodeURIComponent(input.head)}/check-runs?per_page=${limit}`,t);case'workflow_runs':return this.api('GET',`/repos/${repo}/actions/runs?per_page=${limit}`,t);case'issues':return this.api('GET',`/repos/${repo}/issues?state=${input.state??'open'}&per_page=${limit}`,t);case'create_issue':if(!input.title)throw new Error('title is required.');return this.api('POST',`/repos/${repo}/issues`,t,{title:input.title,body:input.body??''});default:throw new Error('Unknown GitHub action.')}}
}
