import {localRecordId,localMissionParent,readLocalObject,assertLocalRecordParent} from './local-mission-parent.js';
import fs from 'node:fs/promises';import path from 'node:path';import crypto from 'node:crypto';import {PgStateStore} from './pg-state.js';
export interface MissionHandoff{schemaVersion:'fs-remote.handoff.v1';id:string;workspaceId?:string;missionId:string;alias?:string;createdAt:string;goal:string;currentStepId?:string;completed:string[];decisions:string[];blockers:string[];pendingQuestions:string[];nextActions:string[];branch?:string;head?:string;notes?:string;metadata:Record<string,unknown>}
const clean=localRecordId;
export class HandoffStore{private readonly pg:PgStateStore;constructor(private readonly missionBase:string,private readonly workspaceId?:string){this.pg=new PgStateStore(workspaceId)} private dir(id:string){return path.join(this.missionBase,clean(id))}
 async save(input:Omit<MissionHandoff,'schemaVersion'|'id'|'createdAt'>){if(this.workspaceId&&input.workspaceId&&input.workspaceId!==this.workspaceId)throw new Error('Cross-workspace handoff denied.');const record:MissionHandoff={schemaVersion:'fs-remote.handoff.v1',id:`handoff-${Date.now()}-${crypto.randomBytes(3).toString('hex')}`,createdAt:new Date().toISOString(),...input,workspaceId:this.workspaceId??input.workspaceId};if(this.pg.enabled()){const stored=await this.pg.saveHandoff(record);record.workspaceId=stored?.workspaceId;return record}const parent=await localMissionParent(this.missionBase,input.missionId,record.workspaceId,input.currentStepId);record.workspaceId=parent.workspaceId;const d=path.join(this.dir(input.missionId),'handoffs');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,`${record.id}.json`),JSON.stringify(record,null,2),'utf8');await fs.writeFile(path.join(this.dir(input.missionId),'latest-handoff.json'),JSON.stringify(record,null,2),'utf8');await this.pg.saveHandoff(record);return record}
 private async localHandoff(file:string,mission:import('./missions.js').Mission){const record=await readLocalObject(file,'handoff');if(!record)return null;if(record.schemaVersion!=='fs-remote.handoff.v1'||typeof record.id!=='string')throw new Error('Invalid local handoff identity.');assertLocalRecordParent({...record,stepId:record.currentStepId},mission);return record as unknown as MissionHandoff}
 async latest(missionId:string){const p=await this.pg.handoffs(missionId);if(p!==null)return p[0]??null;const parent=await localMissionParent(this.missionBase,missionId,this.workspaceId);return this.localHandoff(path.join(this.dir(missionId),'latest-handoff.json'),parent)}
 async list(missionId:string){const p=await this.pg.handoffs(missionId);if(p)return p;const parent=await localMissionParent(this.missionBase,missionId,this.workspaceId),dir=path.join(this.dir(missionId),'handoffs');let names:string[];try{names=(await fs.readdir(dir)).filter(x=>x.endsWith('.json')).sort().reverse()}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return [];throw error}const out:MissionHandoff[]=[];for(const name of names){const record=await this.localHandoff(path.join(dir,name),parent);if(!record)throw new Error('Local handoff disappeared during read.');out.push(record)}return out}
}
