import {localRecordId,localMissionParent,assertLocalRecordParent,LocalWorkspaceAccessDenied} from './local-mission-parent.js';
import {localWorkCompletionDir,readLocalWorkCompletion} from './local-work-completion.js';
import fs from 'node:fs/promises';import path from 'node:path';import crypto from 'node:crypto';import {PgStateStore} from './pg-state.js';
export type MissionStatus='planned'|'running'|'blocked'|'awaiting_approval'|'verifying'|'completed'|'failed'|'cancelled';
export type MissionStepStatus='pending'|'running'|'blocked'|'awaiting_approval'|'verifying'|'completed'|'failed'|'skipped';
export interface MissionStep{id:string;title:string;status:MissionStepStatus;acceptance:string[];requiresApproval:boolean;attempts:number;startedAt?:string;completedAt?:string;lastError?:string}
export interface Mission{schemaVersion:'fs-remote.mission.v1';id:string;workspaceId?:string;alias?:string;goal:string;root:string;cwd:string;status:MissionStatus;createdAt:string;updatedAt:string;currentStepId?:string;steps:MissionStep[];maxRemediationAttempts:number;metadata:Record<string,unknown>}
export interface Evidence{schemaVersion:'fs-remote.evidence.v1';id:string;workspaceId?:string;missionId:string;stepId?:string;kind:string;source:string;status:'pass'|'fail'|'info'|'unknown';summary:string;observedAt:string;data?:Record<string,unknown>}
const cleanId=localRecordId;
export class MissionManager{
 private readonly pg:PgStateStore;
 constructor(private readonly base:string,private readonly workspaceId?:string){this.pg=new PgStateStore(workspaceId)}
 private dir(id:string){return path.join(this.base,cleanId(id))} private file(id:string){return path.join(this.dir(id),'mission.json')}
 private async save(m:Mission){m.updatedAt=new Date().toISOString();if(this.pg.enabled()){await this.pg.saveMission(m);return m}await fs.mkdir(this.dir(m.id),{recursive:true});await fs.writeFile(this.file(m.id),JSON.stringify(m,null,2),'utf8');await this.pg.saveMission(m);return m}
 private async event(id:string,type:string,data:Record<string,unknown>={}){await fs.mkdir(this.dir(id),{recursive:true});await fs.appendFile(path.join(this.dir(id),'events.jsonl'),JSON.stringify({timestamp:new Date().toISOString(),type,...data})+'\n','utf8')}
 async create(input:{alias?:string;goal:string;root:string;cwd:string;steps:Array<{title:string;acceptance?:string[];requiresApproval?:boolean}>;maxRemediationAttempts?:number;metadata?:Record<string,unknown>}){if(!input.goal.trim()||!input.steps.length)throw new Error('Mission goal and at least one step are required.');const now=new Date().toISOString(),id=`mission-${now.replace(/[:.]/g,'-')}-${crypto.randomBytes(3).toString('hex')}`;const m:Mission={schemaVersion:'fs-remote.mission.v1',id,workspaceId:this.workspaceId,alias:input.alias?cleanId(input.alias):undefined,goal:input.goal,root:input.root,cwd:input.cwd,status:'planned',createdAt:now,updatedAt:now,steps:input.steps.map((s,i)=>({id:`step-${i+1}`,title:s.title,status:'pending',acceptance:s.acceptance??[],requiresApproval:!!s.requiresApproval,attempts:0})),maxRemediationAttempts:input.maxRemediationAttempts??3,metadata:input.metadata??{}};await this.save(m);await this.event(id,'MISSION_CREATED',{goal:m.goal});return m}
 async get(id:string){const p=await this.pg.getMission(id);if(p)return p;if(this.pg.enabled())throw new Error('Mission not found in this workspace.');return localMissionParent(this.base,id,this.workspaceId)}
 async list(){const p=await this.pg.listMissions();if(p)return p;let names:string[];try{names=(await fs.readdir(this.base,{withFileTypes:true})).filter(x=>x.isDirectory()).map(x=>x.name)}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return [];throw error}const out:Mission[]=[];for(const name of names){try{out.push(await this.get(name))}catch(error){if(!(error instanceof LocalWorkspaceAccessDenied))throw error}}return out.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))}
 async resolve(ref:string){try{return await this.get(ref)}catch{}const matches=(await this.list()).filter(x=>x.alias===ref);if(matches.length===1)return matches[0];if(matches.length>1)throw new Error('Mission alias is ambiguous.');throw new Error(`Mission '${ref}' was not found.`)}
 async setAlias(id:string,alias:string){const a=cleanId(alias),all=await this.list();if(all.some(x=>x.id!==id&&x.alias===a))throw new Error('Mission alias already exists in this instance.');const m=await this.get(id);m.alias=a;await this.save(m);await this.event(id,'MISSION_ALIAS_SET',{alias:a});return m}
 async start(id:string){const m=await this.get(id);if(['completed','cancelled'].includes(m.status))throw new Error('Terminal mission cannot be started.');m.status='running';await this.save(m);await this.event(id,'MISSION_STARTED');return m}
 async next(id:string){const m=await this.get(id);if(['completed','cancelled','failed'].includes(m.status))throw new Error('Terminal mission cannot advance.');if(m.status==='awaiting_approval')throw new Error('Mission is awaiting approval.');if(m.status==='blocked')throw new Error('Mission is blocked; resume it after resolving the blocker.');let s=m.steps.find(x=>x.status==='running'||x.status==='verifying');if(s)return {mission:m,step:s};s=m.steps.find(x=>x.status==='pending');if(!s){m.status=m.steps.every(x=>['completed','skipped'].includes(x.status))?'completed':'blocked';await this.save(m);return {mission:m,step:null};}if(s.requiresApproval){s.status='awaiting_approval';m.status='awaiting_approval';m.currentStepId=s.id;await this.save(m);await this.event(id,'APPROVAL_REQUIRED',{stepId:s.id});return {mission:m,step:s};}s.status='running';s.attempts++;s.startedAt??=new Date().toISOString();m.currentStepId=s.id;m.status='running';await this.save(m);await this.event(id,'STEP_STARTED',{stepId:s.id,attempt:s.attempts});return {mission:m,step:s}}

 async requirementChallenge(id:string,stepId:string,challenge:Record<string,unknown>){const m=await this.get(id),s=m.steps.find(x=>x.id===stepId);if(!s)throw new Error('Unknown mission step.');s.status='awaiting_approval';s.lastError='Requirement challenge requires user resolution.';m.status='awaiting_approval';m.currentStepId=stepId;m.metadata={...m.metadata,requirementChallenge:challenge};await this.save(m);await this.event(id,'REQUIREMENT_CHALLENGED',{stepId,challenge});return m}
 async overrideRequirement(id:string,stepId:string,note:string,actor='user'){if(!note.trim())throw new Error('Requirement override requires an explicit rationale.');const m=await this.get(id),s=m.steps.find(x=>x.id===stepId);if(!s||s.status!=='awaiting_approval')throw new Error('Requirement is not awaiting resolution.');const challenge=(m.metadata as any).requirementChallenge;if(!challenge)throw new Error('No requirement challenge is recorded.');s.status='running';s.lastError=undefined;s.attempts++;s.startedAt??=new Date().toISOString();m.status='running';m.metadata={...m.metadata,requirementChallenge:undefined,requirementOverrides:[...((m.metadata as any).requirementOverrides??[]),{stepId,actor,note,challenge,at:new Date().toISOString()}]};await this.save(m);await this.event(id,'REQUIREMENT_OVERRIDE_GRANTED',{stepId,actor,note,challenge});return m}
 async approve(id:string,stepId:string,approved:boolean,note=''){const m=await this.get(id),s=m.steps.find(x=>x.id===stepId);if(!s||s.status!=='awaiting_approval')throw new Error('Step is not awaiting approval.');if(approved){s.status='running';s.attempts++;s.startedAt??=new Date().toISOString();m.status='running'}else{s.status='blocked';s.lastError=note||'Approval denied';m.status='blocked'}await this.save(m);await this.event(id,approved?'APPROVAL_GRANTED':'APPROVAL_DENIED',{stepId,note});return m}
 async verify(id:string,stepId:string,passed:boolean,summary:string){const m=await this.get(id),s=m.steps.find(x=>x.id===stepId);if(!s)throw new Error('Unknown mission step.');if(passed){s.status='completed';s.completedAt=new Date().toISOString();s.lastError=undefined;m.currentStepId=undefined;m.status=m.steps.every(x=>['completed','skipped'].includes(x.status))?'completed':'running'}else if(s.attempts<m.maxRemediationAttempts){s.status='pending';s.lastError=summary;m.currentStepId=undefined;m.status='running'}else{s.status='failed';s.lastError=summary;m.status='failed'}await this.save(m);await this.event(id,passed?'STEP_VERIFIED':'STEP_VERIFICATION_FAILED',{stepId,summary,attempt:s.attempts});return m}
 async block(id:string,reason:string){const m=await this.get(id);m.status='blocked';const s=m.steps.find(x=>x.id===m.currentStepId);if(s){s.status='blocked';s.lastError=reason}await this.save(m);await this.event(id,'MISSION_BLOCKED',{reason});return m}
 async resume(id:string){const m=await this.get(id);if(m.status!=='blocked'&&m.status!=='failed')throw new Error('Only blocked or failed missions can be resumed.');const s=m.steps.find(x=>x.status==='blocked'||x.status==='failed');if(s){s.status='pending';s.lastError=undefined}m.status='running';m.currentStepId=undefined;m.metadata={...m.metadata,userInterrupted:false,userInterruptQuestion:undefined};await this.save(m);await this.event(id,'MISSION_RESUMED');return m}
 async interrupt(id:string,question=''){const m=await this.get(id);const s=m.steps.find(x=>x.id===m.currentStepId);if(s){s.status='blocked';s.lastError=question||'Paused by user interruption.'}m.status='blocked';m.metadata={...m.metadata,userInterrupted:true,userInterruptQuestion:question,userInterruptedAt:new Date().toISOString()};await this.save(m);await this.event(id,'MISSION_USER_INTERRUPTED',{question});return m}
 async cancel(id:string,reason=''){const m=await this.get(id);m.status='cancelled';await this.save(m);await this.event(id,'MISSION_CANCELLED',{reason});return m}
 async addEvidence(e:Omit<Evidence,'schemaVersion'|'id'|'observedAt'>){if(this.workspaceId&&e.workspaceId&&this.workspaceId!==e.workspaceId)throw new Error('Cross-workspace evidence denied.');const workspaceId=this.workspaceId??e.workspaceId??(this.pg.enabled()?(await this.pg.getMission(e.missionId))?.workspaceId:undefined);const id=`evidence-${Date.now()}-${crypto.randomBytes(3).toString('hex')}`,record:Evidence={schemaVersion:'fs-remote.evidence.v1',id,observedAt:new Date().toISOString(),...e,workspaceId};if(this.pg.enabled()){const stored=await this.pg.addEvidence(record);record.workspaceId=stored?.workspaceId;return record}const parent=await localMissionParent(this.base,e.missionId,workspaceId,e.stepId);record.workspaceId=parent.workspaceId;await fs.mkdir(this.dir(e.missionId),{recursive:true});await fs.appendFile(path.join(this.dir(e.missionId),'evidence.jsonl'),JSON.stringify(record)+'\n','utf8');await this.event(e.missionId,'EVIDENCE_RECORDED',{evidenceId:id,kind:e.kind,status:e.status,stepId:e.stepId});return record}
 async evidence(id:string){
  const durable=await this.pg.evidence(id);if(durable)return durable;
  let parent:Mission;try{parent=await localMissionParent(this.base,id,this.workspaceId)}catch(error){if(error instanceof LocalWorkspaceAccessDenied)return [];throw error}
  const records:Evidence[]=[];let text:string|undefined;
  try{text=await fs.readFile(path.join(this.dir(id),'evidence.jsonl'),'utf8')}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw new Error('Unable to read local evidence history.')}
  if(text!==undefined)for(const line of text.split(/\r?\n/).filter(x=>x.trim())){
   let record:Evidence;try{record=JSON.parse(line)}catch{throw new Error('Corrupt local evidence history.')}
   if(!record||record.schemaVersion!=='fs-remote.evidence.v1'||!record.id)throw new Error('Invalid local evidence record.');
   assertLocalRecordParent(record,parent);records.push(record);
  }
  const completionDir=localWorkCompletionDir(this.base,id);let names:string[]=[];
  try{names=(await fs.readdir(completionDir)).filter(name=>name.endsWith('.json')).sort()}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw new Error('Unable to read local completion evidence.')}
  for(const name of names){
   const workId=name.slice(0,-5),completion=await readLocalWorkCompletion(path.join(completionDir,name),workId);if(!completion)throw new Error('Local completion evidence disappeared during read.');
   assertLocalRecordParent(completion,parent);
   for(const record of completion.evidence){assertLocalRecordParent(record,parent);records.push(record)}
  }
  const ids=new Set<string>();for(const record of records){if(ids.has(record.id))throw new Error('Duplicate local evidence identity.');ids.add(record.id)}
  return records.map((record,index)=>({record,index})).sort((a,b)=>a.record.observedAt.localeCompare(b.record.observedAt)||a.index-b.index).map(x=>x.record);
 }
 async summary(id:string){const mission=await this.get(id),evidence=await this.evidence(id);return {mission,evidence,counts:{steps:mission.steps.length,completed:mission.steps.filter(x=>x.status==='completed').length,evidence:evidence.length,passedEvidence:evidence.filter(x=>x.status==='pass').length,failedEvidence:evidence.filter(x=>x.status==='fail').length},resumeHint:mission.status==='blocked'?'Resolve blocker then resume.':mission.status==='awaiting_approval'?'Approval required before execution continues.':mission.status==='completed'?'Mission complete; retain evidence for acceptance.':'Call next to continue from durable state.'}}
}
