import {db,databaseEnabled} from './db.js';
export async function migrateMultiUserSchema(){if(!databaseEnabled())return {enabled:false,version:2};await db().query(`
CREATE TABLE IF NOT EXISTS users(id text PRIMARY KEY,username text NOT NULL UNIQUE,email text UNIQUE,password_hash text NOT NULL,status text NOT NULL DEFAULT 'active' CHECK(status IN ('active','disabled','locked')),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS workspaces(id text PRIMARY KEY,slug text NOT NULL UNIQUE,name text NOT NULL,owner_user_id text NOT NULL REFERENCES users(id),status text NOT NULL DEFAULT 'active' CHECK(status IN ('active','suspended')),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS workspace_memberships(workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,role text NOT NULL CHECK(role IN ('owner','admin','engineer','reviewer','viewer')),created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(workspace_id,user_id));
CREATE TABLE IF NOT EXISTS invitations(id text PRIMARY KEY,token_hash text NOT NULL UNIQUE,workspace_id text REFERENCES workspaces(id) ON DELETE CASCADE,intended_email text,role text NOT NULL DEFAULT 'engineer' CHECK(role IN ('owner','admin','engineer','reviewer','viewer')),expires_at timestamptz NOT NULL,max_uses integer NOT NULL DEFAULT 1 CHECK(max_uses>0),use_count integer NOT NULL DEFAULT 0 CHECK(use_count>=0),created_by text REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),consumed_at timestamptz);
CREATE TABLE IF NOT EXISTS user_sessions(id text PRIMARY KEY,token_hash text NOT NULL UNIQUE,user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,workspace_id text REFERENCES workspaces(id) ON DELETE CASCADE,expires_at timestamptz NOT NULL,revoked_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),last_seen_at timestamptz NOT NULL DEFAULT now(),metadata jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS password_reset_tokens(id text PRIMARY KEY,token_hash text NOT NULL UNIQUE,user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires_at timestamptz NOT NULL,consumed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),requested_by text);
ALTER TABLE missions ADD COLUMN IF NOT EXISTS workspace_id text REFERENCES workspaces(id);ALTER TABLE work_items ADD COLUMN IF NOT EXISTS workspace_id text REFERENCES workspaces(id);ALTER TABLE evidence ADD COLUMN IF NOT EXISTS workspace_id text REFERENCES workspaces(id);ALTER TABLE handoffs ADD COLUMN IF NOT EXISTS workspace_id text REFERENCES workspaces(id);ALTER TABLE approvals ADD COLUMN IF NOT EXISTS workspace_id text REFERENCES workspaces(id);ALTER TABLE council_runs ADD COLUMN IF NOT EXISTS workspace_id text REFERENCES workspaces(id);ALTER TABLE execution_nodes ADD COLUMN IF NOT EXISTS workspace_id text REFERENCES workspaces(id);ALTER TABLE node_jobs ADD COLUMN IF NOT EXISTS workspace_id text REFERENCES workspaces(id);ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS workspace_id text REFERENCES workspaces(id);
CREATE TABLE IF NOT EXISTS provider_credentials(workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,provider text NOT NULL,label text,secret_envelope jsonb NOT NULL,status text NOT NULL DEFAULT 'active' CHECK(status IN ('active','disabled')),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(workspace_id,user_id,provider));
CREATE TABLE IF NOT EXISTS user_model_preferences(workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,provider text NOT NULL,model_id text,purpose text NOT NULL CHECK(purpose IN ('developer','reviewer','specialist','adjudicator')),cost_policy text NOT NULL DEFAULT 'free_first' CHECK(cost_policy IN ('free_first','paid_if_consented','external_developer')),paid_consent boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(workspace_id,user_id,purpose));
CREATE TABLE IF NOT EXISTS oauth_connections(id text PRIMARY KEY,workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,client_id text NOT NULL,scopes jsonb NOT NULL DEFAULT '[]'::jsonb,status text NOT NULL DEFAULT 'active' CHECK(status IN ('active','revoked')),created_at timestamptz NOT NULL DEFAULT now(),revoked_at timestamptz,UNIQUE(workspace_id,user_id,client_id));
CREATE TABLE IF NOT EXISTS oauth_authorization_codes(code_hash text PRIMARY KEY,workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,client_id text NOT NULL,redirect_uri text NOT NULL,scopes jsonb NOT NULL DEFAULT '[]'::jsonb,expires_at timestamptz NOT NULL,consumed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS oauth_access_tokens(token_hash text PRIMARY KEY,workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,client_id text NOT NULL,scopes jsonb NOT NULL DEFAULT '[]'::jsonb,expires_at timestamptz NOT NULL,revoked_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS node_enrollments(id text PRIMARY KEY,workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,token_hash text NOT NULL UNIQUE,name text NOT NULL,platform text NOT NULL,projects jsonb NOT NULL DEFAULT '[]'::jsonb,capabilities jsonb NOT NULL DEFAULT '[]'::jsonb,expires_at timestamptz NOT NULL,consumed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS missions_workspace_idx ON missions(workspace_id,updated_at DESC);CREATE INDEX IF NOT EXISTS evidence_workspace_idx ON evidence(workspace_id,observed_at DESC);CREATE INDEX IF NOT EXISTS work_items_workspace_idx ON work_items(workspace_id,status,updated_at DESC);CREATE INDEX IF NOT EXISTS execution_nodes_workspace_idx ON execution_nodes(workspace_id,status);
INSERT INTO fs_schema_migrations(version) VALUES(2) ON CONFLICT DO NOTHING;`);return {enabled:true,version:2}}
