import {type FastifyInstance} from 'fastify';import {z} from 'zod';import {NodeRegistry} from './nodes.js';import type {AppConfig} from './config.js';import {SlidingWindowLimiter} from './rate-limit.js';
const regBody=z.object({nodeId:z.string().regex(/^[A-Za-z0-9._-]+$/),name:z.string().min(1).max(120),platform:z.string().min(1).max(80),capabilities:z.array(z.enum(['filesystem','command','process','git','browser','docker','database','engineering'])).min(1),projects:z.array(z.string().min(1)).default([]),metadata:z.record(z.string(),z.unknown()).optional()}).strict();
const readinessBody=z.object({schemaVersion:z.literal('fs.node.readiness.v1'),ok:z.boolean(),checkedAt:z.string().datetime(),platform:z.enum(['win32','darwin','linux']),arch:z.string().min(1).max(40),node:z.string().min(1).max(80),shell:z.string().min(1).max(240),checks:z.array(z.object({name:z.string().min(1).max(80),status:z.enum(['pass','warn','fail'])}).strict()).max(32)}).strict();const agentBody=z.object({schemaVersion:z.literal('fs.node.agent.v1'),serviceVersion:z.string().min(1).max(80),protocolVersion:z.number().int().min(0).max(100000),gitCommit:z.string().regex(/^[A-Fa-f0-9]{40}$/).optional(),platform:z.string().min(1).max(80),arch:z.string().min(1).max(40),node:z.string().min(1).max(80),sessionId:z.string().min(8).max(120).optional(),startedAt:z.string().datetime().optional()}).strict();const heartbeatBody=z.object({readiness:readinessBody.optional(),agent:agentBody.optional()}).strict();const claimBody=z.object({leaseMs:z.number().int().min(5000).max(900000).default(120000)}).strict();const renewBody=z.object({jobId:z.string().min(1),leaseToken:z.string().min(20),leaseMs:z.number().int().min(5000).max(900000).default(120000)}).strict();const enqueueBody=z.object({missionId:z.string().min(1),stepId:z.string().min(1),nodeId:z.string().min(1),project:z.string().min(1),capability:z.enum(['filesystem','command','process','git','browser','docker','database','engineering']),operation:z.string().min(1),payload:z.record(z.string(),z.unknown()).default({}),executionTarget:z.enum(['local','sandbox','hosted']).default('local')}).strict();const doneBody=z.object({jobId:z.string().min(1),leaseToken:z.string().min(20),status:z.enum(['completed','failed']).default('completed'),result:z.record(z.string(),z.unknown()).default({})}).strict();
export function registerNodeRoutes(app:FastifyInstance,config:AppConfig){const nodes=new NodeRegistry();const nodeLimiter=new SlidingWindowLimiter(240,60000);const adminLimiter=new SlidingWindowLimiter(120,60000);const admin=async(req:any,reply:any)=>{if(req.headers.authorization!==`Bearer ${config.actionsSecret}`)await reply.code(401).send({error:'Unauthorized.'})};const nodeAuth=(req:any)=>{const id=String(req.headers['x-fs-node-id']??''),secret=String(req.headers['x-fs-node-secret']??'');if(!id||!secret)throw new Error('Node credentials required.');return {id,secret}};
 app.post('/node/register',{preHandler:admin},async(req)=>nodes.register(regBody.parse(req.body)));
 app.get('/node/list',{preHandler:admin},async()=>nodes.list());
 app.get('/node/job/:id',{preHandler:admin},async(req:any)=>nodes.getJob(String(req.params.id)));
 app.post('/node/enqueue',{preHandler:admin},async(req)=>nodes.enqueue(enqueueBody.parse(req.body)));
 app.post('/node/heartbeat',async(req,reply)=>{try{const a=nodeAuth(req),b=heartbeatBody.parse(req.body??{}),identity=await NodeRegistry.resolveIdentity(a.id,a.secret);if(!identity)throw new Error('Invalid node credentials.');return await new NodeRegistry(identity.workspaceId).heartbeat(a.id,a.secret,b.readiness,b.agent)}catch(e){await reply.code(401).send({error:e instanceof Error?e.message:String(e)})}});
 app.post('/node/recover',{preHandler:admin},async()=>nodes.recover());
 app.post('/node/claim',async(req,reply)=>{try{const a=nodeAuth(req),b=claimBody.parse(req.body),identity=await NodeRegistry.resolveIdentity(a.id,a.secret);if(!identity)throw new Error('Invalid node credentials.');return await new NodeRegistry(identity.workspaceId).claim(a.id,a.secret,b.leaseMs)}catch(e){await reply.code(401).send({error:e instanceof Error?e.message:String(e)})}});
 app.post('/node/renew',async(req,reply)=>{try{const a=nodeAuth(req),b=renewBody.parse(req.body),identity=await NodeRegistry.resolveIdentity(a.id,a.secret);if(!identity)throw new Error('Invalid node credentials.');return await new NodeRegistry(identity.workspaceId).renew(a.id,a.secret,b.jobId,b.leaseToken,b.leaseMs)}catch(e){await reply.code(409).send({error:e instanceof Error?e.message:String(e)})}});
 app.post('/node/complete',async(req,reply)=>{try{const a=nodeAuth(req),b=doneBody.parse(req.body),identity=await NodeRegistry.resolveIdentity(a.id,a.secret);if(!identity)throw new Error('Invalid node credentials.');return await new NodeRegistry(identity.workspaceId).complete(a.id,a.secret,b.jobId,b.leaseToken,b.result,b.status)}catch(e){await reply.code(401).send({error:e instanceof Error?e.message:String(e)})}});
}
