import crypto from 'node:crypto';import {db,databaseEnabled} from './db.js';
export type NodeCapability='filesystem'|'command'|'process'|'git'|'browser'|'docker'|'database';
export interface NodeRegistration{nodeId:string;workspaceId?:string;name:string;platform:string;capabilities:NodeCapability[];projects:string[];metadata?:Record<string,unknown>}
const iid=()=>process.env.FS_REMOTE_INSTANCE_ID??'v3-default';
export class NodeRegistry{
 constructor(private readonly workspaceId?:string){}
 private workspace(){return this.workspaceId??null}
 async register(x:NodeRegistration){if(!databaseEnabled())throw new Error('Node protocol requires DATABASE_URL.');const secret=crypto.randomBytes(32).toString('base64url'),hash=crypto.createHash('sha256').update(secret).digest('hex');await db().query(`INSERT INTO execution_nodes(id,instance_id,name,platform,capabilities,projects,credential_hash,status,last_seen_at,metadata,workspace_id) VALUES($1,$2,$3,$4,$5,$6,$7,'online',now(),$8,$9) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,platform=EXCLUDED.platform,capabilities=EXCLUDED.capabilities,projects=EXCLUDED.projects,credential_hash=EXCLUDED.credential_hash,status='online',last_seen_at=now(),metadata=EXCLUDED.metadata,workspace_id=EXCLUDED.workspace_id`,[x.nodeId,iid(),x.name,x.platform,JSON.stringify(x.capabilities),JSON.stringify(x.projects),hash,x.metadata??{},this.workspace()]);return {nodeId:x.nodeId,nodeSecret:secret}}
 async authenticate(nodeId:string,secret:string){const hash=crypto.createHash('sha256').update(secret).digest('hex');const r=await db().query("UPDATE execution_nodes SET last_seen_at=now(),status='online' WHERE id=$1 AND instance_id=$2 AND credential_hash=$3 AND ($4::text IS NULL OR workspace_id=$4) RETURNING *",[nodeId,iid(),hash,this.workspace()]);return r.rows[0]??null}
 async heartbeat(nodeId:string,secret:string){const n=await this.authenticate(nodeId,secret);if(!n)throw new Error('Invalid node credentials.');return {nodeId,status:'online',at:new Date().toISOString()}}
 async list(){const offlineMs=Number(process.env.FS_REMOTE_NODE_OFFLINE_MS??45000);await db().query("UPDATE execution_nodes SET status='offline' WHERE instance_id=$1 AND ($3::text IS NULL OR workspace_id=$3) AND last_seen_at < now()-($2::text||' milliseconds')::interval",[iid(),offlineMs,this.workspace()]);const r=await db().query('SELECT id,name,platform,capabilities,projects,status,last_seen_at,metadata FROM execution_nodes WHERE instance_id=$1 AND ($2::text IS NULL OR workspace_id=$2) ORDER BY name',[iid(),this.workspace()]);return r.rows}
 async getJob(id:string){const r=await db().query('SELECT id,node_id,project,mission_id,step_id,capability,operation,status,attempts,result,created_at,updated_at,completed_at FROM node_jobs WHERE id=$1 AND instance_id=$2 AND ($3::text IS NULL OR workspace_id=$3)',[id,iid(),this.workspace()]);return r.rows[0]??null}
 async recover(){const r=await db().query("UPDATE node_jobs SET status='queued',lease_token_hash=NULL,lease_expires_at=NULL,updated_at=now() WHERE instance_id=$1 AND ($2::text IS NULL OR workspace_id=$2) AND status='leased' AND lease_expires_at<now() RETURNING id",[iid(),this.workspace()]);return {recovered:r.rows.map((x:any)=>x.id)}}
 async enqueue(input:{missionId:string;stepId:string;nodeId:string;project:string;capability:NodeCapability;operation:string;payload:Record<string,unknown>},options:{idempotencyKey?:string}={}){const node=await db().query('SELECT * FROM execution_nodes WHERE id=$1 AND instance_id=$2 AND ($3::text IS NULL OR workspace_id=$3)',[input.nodeId,iid(),this.workspace()]);if(!node.rowCount)throw new Error('Execution node not found.');const n=node.rows[0];if(!(n.capabilities??[]).includes(input.capability))throw new Error(`Node does not advertise capability ${input.capability}.`);if((n.projects??[]).length&&!(n.projects??[]).includes(input.project))throw new Error('Node is not authorized for this project.');if(options.idempotencyKey){const existing=await db().query('SELECT id,status FROM node_jobs WHERE instance_id=$1 AND ($3::text IS NULL OR workspace_id=$3) AND idempotency_key=$2',[iid(),options.idempotencyKey,this.workspace()]);if(existing.rowCount)return existing.rows[0]}const id=`nodejob-${Date.now()}-${crypto.randomBytes(4).toString('hex')}`;await db().query(`INSERT INTO node_jobs(id,instance_id,node_id,project,mission_id,step_id,capability,operation,payload,status,created_at,updated_at,idempotency_key,workspace_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'queued',now(),now(),$10,$11)`,[id,iid(),input.nodeId,input.project,input.missionId,input.stepId,input.capability,input.operation,input.payload,options.idempotencyKey??null,this.workspace()]);return {id,status:'queued'}}
 async claim(nodeId:string,secret:string,leaseMs=120000){const node=await this.authenticate(nodeId,secret);if(!node)throw new Error('Invalid node credentials.');await this.recover();const token=crypto.randomBytes(24).toString('base64url'),c=await db().connect();try{await c.query('BEGIN');const r=await c.query(`SELECT * FROM node_jobs WHERE instance_id=$1 AND node_id=$2 AND ($3::text IS NULL OR workspace_id=$3) AND status='queued' ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1`,[iid(),nodeId,this.workspace()]);if(!r.rowCount){await c.query('COMMIT');return null}const u=await c.query(`UPDATE node_jobs SET status='leased',lease_token_hash=$2,lease_expires_at=now()+($3::text||' milliseconds')::interval,attempts=attempts+1,updated_at=now() WHERE id=$1 RETURNING *`,[r.rows[0].id,crypto.createHash('sha256').update(token).digest('hex'),leaseMs]);await c.query('COMMIT');return {...u.rows[0],leaseToken:token,lease_token_hash:undefined}}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
 async complete(nodeId:string,secret:string,jobId:string,leaseToken:string,result:Record<string,unknown>,status:'completed'|'failed'='completed'){if(!await this.authenticate(nodeId,secret))throw new Error('Invalid node credentials.');const h=crypto.createHash('sha256').update(leaseToken).digest('hex');const r=await db().query(`UPDATE node_jobs SET status=$4,result=$5,lease_token_hash=NULL,lease_expires_at=NULL,updated_at=now(),completed_at=now() WHERE id=$1 AND instance_id=$2 AND node_id=$3 AND lease_token_hash=$6 AND lease_expires_at>=now() AND ($7::text IS NULL OR workspace_id=$7) RETURNING *`,[jobId,iid(),nodeId,status,result,h,this.workspace()]);if(!r.rowCount)throw new Error('Invalid or expired node job lease.');const job=r.rows[0],eid=`node-${job.id}`,retrieval=job.payload?.__retrieval,verification=job.payload?.__verification,kind=retrieval?'repository_context':verification?'reliability_verification':'node_execution',summary=retrieval?`Repository retrieval ${retrieval.phase} ${status}.`:verification?`Independent verification run ${verification.run} ${status}.`:`Node ${nodeId} ${status} ${job.capability}/${job.operation}.`;await db().query(`INSERT INTO evidence(id,instance_id,mission_id,step_id,kind,source,status,summary,payload,observed_at,workspace_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,now(),$10) ON CONFLICT(id) DO NOTHING`,[eid,iid(),job.mission_id,job.step_id,kind,`node:${nodeId}`,status==='completed'?'pass':'fail',summary,{jobId:job.id,project:job.project,capability:job.capability,operation:job.operation,retrieval,verification,result,verificationRecipe:verification?.recipe},this.workspace()]);return job}
}