import crypto from 'node:crypto';
import {NodeProtocolError,nodeProtocolFailure} from './node-protocol-error.js';
import {type FastifyInstance,type FastifyReply} from 'fastify';import {z} from 'zod';import {NodeRegistry} from './nodes.js';import type {AppConfig} from './config.js';import {SlidingWindowLimiter} from './rate-limit.js';
const regBody=z.object({nodeId:z.string().regex(/^[A-Za-z0-9._-]+$/),name:z.string().min(1).max(120),platform:z.string().min(1).max(80),capabilities:z.array(z.enum(['filesystem','command','process','git','browser','docker','database','engineering'])).min(1),projects:z.array(z.string().min(1)).default([]),metadata:z.record(z.string(),z.unknown()).optional()}).strict();
const readinessBody=z.object({schemaVersion:z.literal('fs.node.readiness.v1'),ok:z.boolean(),checkedAt:z.string().datetime(),platform:z.enum(['win32','darwin','linux']),arch:z.string().min(1).max(40),node:z.string().min(1).max(80),shell:z.string().min(1).max(240),checks:z.array(z.object({name:z.string().min(1).max(80),status:z.enum(['pass','warn','fail'])}).strict()).max(32)}).strict();const agentBody=z.object({schemaVersion:z.literal('fs.node.agent.v1'),serviceVersion:z.string().min(1).max(80),protocolVersion:z.number().int().min(0).max(100000),gitCommit:z.string().regex(/^[A-Fa-f0-9]{40}$/).optional(),platform:z.string().min(1).max(80),arch:z.string().min(1).max(40),node:z.string().min(1).max(80),sessionId:z.string().min(8).max(120).optional(),startedAt:z.string().datetime().optional()}).strict();const heartbeatBody=z.object({readiness:readinessBody.optional(),agent:agentBody.optional()}).strict();const claimBody=z.object({leaseMs:z.number().int().min(5000).max(900000).default(120000)}).strict();const renewBody=z.object({jobId:z.string().min(1),leaseToken:z.string().min(20),leaseMs:z.number().int().min(5000).max(900000).default(120000)}).strict();const enqueueBody=z.object({missionId:z.string().min(1),stepId:z.string().min(1),nodeId:z.string().min(1),project:z.string().min(1),capability:z.enum(['filesystem','command','process','git','browser','docker','database','engineering']),operation:z.string().min(1),payload:z.record(z.string(),z.unknown()).default({}),executionTarget:z.enum(['local','sandbox','hosted']).default('local')}).strict();const doneBody=z.object({jobId:z.string().min(1),leaseToken:z.string().min(20),status:z.enum(['completed','failed']).default('completed'),result:z.record(z.string(),z.unknown()).default({})}).strict();
function adminAuthorized(header:unknown,secret:unknown){if(typeof secret!=='string'||!secret.trim()||typeof header!=='string')return false;const hash=(text:string)=>crypto.createHash('sha256').update(text).digest();return crypto.timingSafeEqual(hash(header),hash(`Bearer ${secret}`));}
async function nodeResponse<T>(reply:FastifyReply,run:()=>Promise<T>){try{return await run()}catch(error){const failure=nodeProtocolFailure(error);return reply.code(failure.statusCode).send({error:failure.error,code:failure.code})}}
export function registerNodeRoutes(app:FastifyInstance,config:AppConfig){const nodes=new NodeRegistry();const nodeLimiter=new SlidingWindowLimiter(240,60000);const adminLimiter=new SlidingWindowLimiter(120,60000);const admin=async(req:any,reply:any)=>{if(!adminAuthorized(req.headers.authorization,config.actionsSecret))await reply.code(401).send({error:'Unauthorized.'})};const nodeAuth=(req:any)=>{const id=String(req.headers['x-fs-node-id']??''),secret=String(req.headers['x-fs-node-secret']??'');if(!id||!secret)throw new NodeProtocolError('NODE_CREDENTIALS_INVALID');return {id,secret}};
 app.addHook('onRequest',async(req,reply)=>{if(!req.url.startsWith('/node/'))return;const nodePath=['/node/heartbeat','/node/claim','/node/renew','/node/complete'].includes(req.url.split('?')[0]);const budget=(nodePath?nodeLimiter:adminLimiter).allow(String(req.ip));if(!budget.allowed)return reply.header('retry-after',String(Math.ceil(budget.retryAfterMs/1000))).code(429).send({error:'Too many node requests.'})});
 app.post('/node/register',{preHandler:admin},async(req,reply)=>nodeResponse(reply,()=>nodes.register(regBody.parse(req.body))));
 app.get('/node/list',{preHandler:admin},async(_req,reply)=>nodeResponse(reply,()=>nodes.list()));
 app.get('/node/job/:id',{preHandler:admin},async(req:any,reply)=>nodeResponse(reply,()=>nodes.getJob(String(req.params.id))));
 app.post('/node/job/:id/retry',{preHandler:admin},async(req:any,reply)=>nodeResponse(reply,()=>nodes.retryJob(String(req.params.id))));
 app.post('/node/enqueue',{preHandler:admin},async(req,reply)=>nodeResponse(reply,()=>nodes.enqueue(enqueueBody.parse(req.body))));
 app.post('/node/heartbeat',async(req,reply)=>{try{const a=nodeAuth(req),b=heartbeatBody.parse(req.body??{}),identity=await NodeRegistry.resolveIdentity(a.id,a.secret);if(!identity)throw new NodeProtocolError('NODE_CREDENTIALS_INVALID');return await new NodeRegistry(identity.workspaceId).heartbeat(a.id,a.secret,b.readiness,b.agent)}catch(e){const failure=nodeProtocolFailure(e);return reply.code(failure.statusCode).send({error:failure.error,code:failure.code})}});
 app.post('/node/recover',{preHandler:admin},async(_req,reply)=>nodeResponse(reply,()=>nodes.recover()));
 app.post('/node/claim',async(req,reply)=>{try{const a=nodeAuth(req),b=claimBody.parse(req.body),identity=await NodeRegistry.resolveIdentity(a.id,a.secret);if(!identity)throw new NodeProtocolError('NODE_CREDENTIALS_INVALID');return await new NodeRegistry(identity.workspaceId).claim(a.id,a.secret,b.leaseMs)}catch(e){const failure=nodeProtocolFailure(e);return reply.code(failure.statusCode).send({error:failure.error,code:failure.code})}});
 app.post('/node/renew',async(req,reply)=>{try{const a=nodeAuth(req),b=renewBody.parse(req.body),identity=await NodeRegistry.resolveIdentity(a.id,a.secret);if(!identity)throw new NodeProtocolError('NODE_CREDENTIALS_INVALID');return await new NodeRegistry(identity.workspaceId).renew(a.id,a.secret,b.jobId,b.leaseToken,b.leaseMs)}catch(e){const failure=nodeProtocolFailure(e);return reply.code(failure.statusCode).send({error:failure.error,code:failure.code})}});
 app.post('/node/complete',async(req,reply)=>{try{const a=nodeAuth(req),b=doneBody.parse(req.body),identity=await NodeRegistry.resolveIdentity(a.id,a.secret);if(!identity)throw new NodeProtocolError('NODE_CREDENTIALS_INVALID');return await new NodeRegistry(identity.workspaceId).complete(a.id,a.secret,b.jobId,b.leaseToken,b.result,b.status)}catch(e){const failure=nodeProtocolFailure(e);return reply.code(failure.statusCode).send({error:failure.error,code:failure.code})}});
}
