import {type FastifyInstance} from 'fastify';import {z} from 'zod';import {NodeRegistry} from './nodes.js';import type {AppConfig} from './config.js';
const regBody=z.object({nodeId:z.string().regex(/^[A-Za-z0-9._-]+$/),name:z.string().min(1).max(120),platform:z.string().min(1).max(80),capabilities:z.array(z.enum(['filesystem','command','process','git','browser','docker','database'])).min(1),projects:z.array(z.string().min(1)).default([]),metadata:z.record(z.string(),z.unknown()).optional()}).strict();
const claimBody=z.object({leaseMs:z.number().int().min(5000).max(900000).default(120000)}).strict();const enqueueBody=z.object({missionId:z.string().min(1),stepId:z.string().min(1),nodeId:z.string().min(1),project:z.string().min(1),capability:z.enum(['filesystem','command','process','git','browser','docker','database']),operation:z.string().min(1),payload:z.record(z.string(),z.unknown()).default({})}).strict();const doneBody=z.object({jobId:z.string().min(1),leaseToken:z.string().min(20),status:z.enum(['completed','failed']).default('completed'),result:z.record(z.string(),z.unknown()).default({})}).strict();
export function registerNodeRoutes(app:FastifyInstance,config:AppConfig){const nodes=new NodeRegistry();const admin=async(req:any,reply:any)=>{if(req.headers.authorization!==`Bearer ${config.actionsSecret}`)await reply.code(401).send({error:'Unauthorized.'})};const nodeAuth=(req:any)=>{const id=String(req.headers['x-fs-node-id']??''),secret=String(req.headers['x-fs-node-secret']??'');if(!id||!secret)throw new Error('Node credentials required.');return {id,secret}};
 app.post('/node/register',{preHandler:admin},async(req)=>nodes.register(regBody.parse(req.body)));
 app.get('/node/list',{preHandler:admin},async()=>nodes.list());
 app.get('/node/job/:id',{preHandler:admin},async(req:any)=>nodes.getJob(String(req.params.id)));
 app.post('/node/enqueue',{preHandler:admin},async(req)=>nodes.enqueue(enqueueBody.parse(req.body)));
 app.post('/node/heartbeat',async(req,reply)=>{try{const a=nodeAuth(req);return await nodes.heartbeat(a.id,a.secret)}catch(e){await reply.code(401).send({error:e instanceof Error?e.message:String(e)})}});
 app.post('/node/recover',{preHandler:admin},async()=>nodes.recover());
 app.post('/node/claim',async(req,reply)=>{try{const a=nodeAuth(req),b=claimBody.parse(req.body);return await nodes.claim(a.id,a.secret,b.leaseMs)}catch(e){await reply.code(401).send({error:e instanceof Error?e.message:String(e)})}});
 app.post('/node/complete',async(req,reply)=>{try{const a=nodeAuth(req),b=doneBody.parse(req.body);return await nodes.complete(a.id,a.secret,b.jobId,b.leaseToken,b.result,b.status)}catch(e){await reply.code(401).send({error:e instanceof Error?e.message:String(e)})}});
}