import crypto from 'node:crypto';import {db,databaseEnabled} from './db.js';
export type NodeCapability='filesystem'|'command'|'process'|'git'|'browser'|'docker'|'database';
export interface NodeRegistration{nodeId:string;name:string;platform:string;capabilities:NodeCapability[];projects:string[];metadata?:Record<string,unknown>}
const iid=()=>process.env.FS_REMOTE_INSTANCE_ID??'v3-default';
export class NodeRegistry{
 async register(x:NodeRegistration){if(!databaseEnabled())throw new Error('Node protocol requires DATABASE_URL.');const secret=crypto.randomBytes(32).toString('base64url'),hash=crypto.createHash('sha256').update(secret).digest('hex');await db().query(`INSERT INTO execution_nodes(id,instance_id,name,platform,capabilities,projects,credential_hash,status,last_seen_at,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,'online',now(),$8) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,platform=EXCLUDED.platform,capabilities=EXCLUDED.capabilities,projects=EXCLUDED.projects,credential_hash=EXCLUDED.credential_hash,status='online',last_seen_at=now(),metadata=EXCLUDED.metadata`,[x.nodeId,iid(),x.name,x.platform,JSON.stringify(x.capabilities),JSON.stringify(x.projects),hash,x.metadata??{}]);return {nodeId:x.nodeId,nodeSecret:secret}}
 async authenticate(nodeId:string,secret:string){const hash=crypto.createHash('sha256').update(secret).digest('hex');const r=await db().query('UPDATE execution_nodes SET last_seen_at=now(),status=\'online\' WHERE id=$1 AND instance_id=$2 AND credential_hash=$3 RETURNING *',[nodeId,iid(),hash]);return r.rows[0]??null}
 async list(){const r=await db().query('SELECT id,name,platform,capabilities,projects,status,last_seen_at,metadata FROM execution_nodes WHERE instance_id=$1 ORDER BY name',[iid()]);return r.rows}
 async getJob(id:string){const r=await db().query('SELECT id,node_id,project,mission_id,step_id,capability,operation,status,attempts,result,created_at,updated_at,completed_at FROM node_jobs WHERE id=$1 AND instance_id=$2',[id,iid()]);return r.rows[0]??null}
 async enqueue(input:{missionId:string;stepId:string;nodeId:string;project:string;capability:NodeCapability;operation:string;payload:Record<string,unknown>}){const node=await db().query('SELECT * FROM execution_nodes WHERE id=$1 AND instance_id=$2',[input.nodeId,iid()]);if(!node.rowCount)throw new Error('Execution node not found.');const n=node.rows[0];if(!(n.capabilities??[]).includes(input.capability))throw new Error(`Node does not advertise capability ${input.capability}.`);if((n.projects??[]).length&&!(n.projects??[]).includes(input.project))throw new Error('Node is not authorized for this project.');const id=`nodejob-${Date.now()}-${crypto.randomBytes(4).toString('hex')}`;await db().query(`INSERT INTO node_jobs(id,instance_id,node_id,project,mission_id,step_id,capability,operation,payload,status,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'queued',now(),now())`,[id,iid(),input.nodeId,input.project,input.missionId,input.stepId,input.capability,input.operation,input.payload]);return {id,status:'queued'}}
 async claim(nodeId:string,secret:string,leaseMs=120000){const node=await this.authenticate(nodeId,secret);if(!node)throw new Error('Invalid node credentials.');const token=crypto.randomBytes(24).toString('base64url'),c=await db().connect();try{await c.query('BEGIN');const r=await c.query(`SELECT * FROM node_jobs WHERE instance_id=$1 AND node_id=$2 AND (status='queued' OR (status='leased' AND lease_expires_at<now())) ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1`,[iid(),nodeId]);if(!r.rowCount){await c.query('COMMIT');return null}const u=await c.query(`UPDATE node_jobs SET status='leased',lease_token_hash=$2,lease_expires_at=now()+($3::text||' milliseconds')::interval,attempts=attempts+1,updated_at=now() WHERE id=$1 RETURNING *`,[r.rows[0].id,crypto.createHash('sha256').update(token).digest('hex'),leaseMs]);await c.query('COMMIT');return {...u.rows[0],leaseToken:token,lease_token_hash:undefined}}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
 async complete(nodeId:string,secret:string,jobId:string,leaseToken:string,result:Record<string,unknown>,status:'completed'|'failed'='completed'){if(!await this.authenticate(nodeId,secret))throw new Error('Invalid node credentials.');const h=crypto.createHash('sha256').update(leaseToken).digest('hex');const r=await db().query(`UPDATE node_jobs SET status=$4,result=$5,lease_token_hash=NULL,lease_expires_at=NULL,updated_at=now(),completed_at=now() WHERE id=$1 AND instance_id=$2 AND node_id=$3 AND lease_token_hash=$6 RETURNING *`,[jobId,iid(),nodeId,status,result,h]);if(!r.rowCount)throw new Error('Invalid or expired node job lease.');return r.rows[0]}
}