import crypto from 'node:crypto';import type {FastifyInstance} from 'fastify';import {AuthStore} from './auth-store.js';import {db} from './db.js';import {hashOpaqueToken,issueOpaqueToken} from './auth-crypto.js';
const esc=(x:string)=>x.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const allowedRedirect=(uri:string)=>{const configured=(process.env.FS_GPT_OAUTH_REDIRECT_URIS??'').split(',').map(x=>x.trim()).filter(Boolean);return configured.includes(uri)};
const clientOk=(id:string)=>!!id&&id===(process.env.FS_GPT_OAUTH_CLIENT_ID??'fs-engineering-gpt');
const scopesFor=(role:string)=>role==='owner'||role==='admin'?['fs.read','fs.write','fs.node','fs.models','fs.admin']:role==='engineer'?['fs.read','fs.write','fs.node','fs.models']:['fs.read'];
export async function resolveOAuthAccessToken(token:string){if(!token)return null;const r=await db().query(`SELECT t.user_id,t.workspace_id,t.scopes,u.username,m.role FROM oauth_access_tokens t JOIN users u ON u.id=t.user_id JOIN workspace_memberships m ON m.user_id=t.user_id AND m.workspace_id=t.workspace_id WHERE t.token_hash=$1 AND t.revoked_at IS NULL AND t.expires_at>now() AND u.status='active'`,[hashOpaqueToken(token)]);return r.rows[0]??null}
export function registerOAuthRoutes(app:FastifyInstance){const auth=new AuthStore();
 app.get('/oauth/authorize',async(r:any,reply)=>{const q=r.query??{},clientId=String(q.client_id??''),redirectUri=String(q.redirect_uri??''),state=String(q.state??''),scope=String(q.scope??'fs.read');if(!clientOk(clientId)||!allowedRedirect(redirectUri))return reply.code(400).type('text/html').send('Invalid OAuth client or redirect URI.');return reply.type('text/html').send(`<!doctype html><html><body><main style="max-width:520px;margin:60px auto;font-family:system-ui"><h1>Authorize FS Engineering</h1><p>Sign in to connect your FS workspace to ChatGPT.</p><form id="oauthForm" method="post" action="/oauth/authorize"><input type="hidden" name="client_id" value="${esc(clientId)}"><input type="hidden" name="redirect_uri" value="${esc(redirectUri)}"><input type="hidden" name="state" value="${esc(state)}"><input type="hidden" name="scope" value="${esc(scope)}"><p><input name="username" placeholder="Username" required></p><p><input name="password" type="password" placeholder="Password" required></p><button>Authorize</button></form><p class="muted">Your browser will return to ChatGPT after authorization.</p></main></body></html>`)});
 app.post('/oauth/authorize',async(r:any,reply)=>{const b=r.body??{},clientId=String(b.client_id??''),redirectUri=String(b.redirect_uri??''),state=String(b.state??'');if(!clientOk(clientId)||!allowedRedirect(redirectUri))return reply.code(400).send({error:'invalid_request'});try{const p=await auth.authenticate({username:String(b.username??''),password:String(b.password??'')}),requested=String(b.scope??'fs.read').split(/\s+/).filter(Boolean),allowed=scopesFor(String(p.role)),scopes=requested.filter(x=>allowed.includes(x));if(!scopes.length)scopes.push('fs.read');const code=issueOpaqueToken(),expiresAt=new Date(Date.now()+5*60_000);await db().query(`INSERT INTO oauth_authorization_codes(code_hash,workspace_id,user_id,client_id,redirect_uri,scopes,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7)`,[hashOpaqueToken(code),p.workspaceId,p.userId,clientId,redirectUri,JSON.stringify(scopes),expiresAt]);const u=new URL(redirectUri);u.searchParams.set('code',code);if(state)u.searchParams.set('state',state);return reply.redirect(u.toString())}catch{return reply.code(401).send({error:'access_denied'})}});
 app.post('/oauth/token',async(r:any,reply)=>{const b=r.body??{},clientId=String(b.client_id??''),secret=String(b.client_secret??'');const expected=process.env.FS_GPT_OAUTH_CLIENT_SECRET??'',givenHash=crypto.createHash('sha256').update(secret).digest(),expectedHash=crypto.createHash('sha256').update(expected).digest();if(!clientOk(clientId)||!expected||!crypto.timingSafeEqual(givenHash,expectedHash))return reply.code(401).send({error:'invalid_client'});if(String(b.grant_type??'authorization_code')!=='authorization_code')return reply.code(400).send({error:'unsupported_grant_type'});const c=await db().connect();try{await c.query('BEGIN');const x=(await c.query(`SELECT * FROM oauth_authorization_codes WHERE code_hash=$1 AND client_id=$2 AND redirect_uri=$3 AND consumed_at IS NULL AND expires_at>now() FOR UPDATE`,[hashOpaqueToken(String(b.code??'')),clientId,String(b.redirect_uri??'')])).rows[0];if(!x)throw new Error('invalid_grant');await c.query(`UPDATE oauth_authorization_codes SET consumed_at=now() WHERE code_hash=$1`,[hashOpaqueToken(String(b.code))]);const access=issueOpaqueToken(),expiresAt=new Date(Date.now()+60*60_000);await c.query(`INSERT INTO oauth_access_tokens(token_hash,workspace_id,user_id,client_id,scopes,expires_at) VALUES($1,$2,$3,$4,$5,$6)`,[hashOpaqueToken(access),x.workspace_id,x.user_id,clientId,x.scopes,expiresAt]);await c.query(`INSERT INTO oauth_connections(id,workspace_id,user_id,client_id,scopes,status) VALUES($1,$2,$3,$4,$5,'active') ON CONFLICT(workspace_id,user_id,client_id) DO UPDATE SET scopes=excluded.scopes,status='active',revoked_at=NULL`,[`gpt-${crypto.randomUUID()}`,x.workspace_id,x.user_id,clientId,x.scopes]);await c.query('COMMIT');return {access_token:access,token_type:'bearer',expires_in:3600,scope:(x.scopes??[]).join(' ')}}catch{await c.query('ROLLBACK');return reply.code(400).send({error:'invalid_grant'})}finally{c.release()}});
}
