import crypto from 'node:crypto';import {db,databaseEnabled} from './db.js';import type {Mission,MissionStep,Evidence} from './missions.js';import type {WorkItem} from './workers.js';import type {MissionHandoff} from './handoff.js';
const iid=()=>process.env.FS_REMOTE_INSTANCE_ID??'v3-default';
export class PgStateStore{
 constructor(private readonly workspaceId?:string){}
 private workspace(){return this.workspaceId??null}
 enabled(){return databaseEnabled()}
 async saveMission(m:Mission){if(!this.enabled())return;const c=await db().connect();try{await c.query('BEGIN');await c.query(`INSERT INTO missions(id,instance_id,alias,goal,root,cwd,status,current_step_id,max_remediation_attempts,metadata,created_at,updated_at,workspace_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT(id) DO UPDATE SET alias=EXCLUDED.alias,goal=EXCLUDED.goal,root=EXCLUDED.root,cwd=EXCLUDED.cwd,status=EXCLUDED.status,current_step_id=EXCLUDED.current_step_id,max_remediation_attempts=EXCLUDED.max_remediation_attempts,metadata=EXCLUDED.metadata,workspace_id=EXCLUDED.workspace_id,updated_at=EXCLUDED.updated_at`,[m.id,iid(),m.alias??null,m.goal,m.root,m.cwd,m.status,m.currentStepId??null,m.maxRemediationAttempts,m.metadata,m.createdAt,m.updatedAt,this.workspace()]);await c.query('DELETE FROM mission_steps WHERE mission_id=$1',[m.id]);for(let i=0;i<m.steps.length;i++){const s=m.steps[i];await c.query(`INSERT INTO mission_steps(id,mission_id,ordinal,title,acceptance,requires_approval,status,attempts,started_at,completed_at,last_error) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[`${m.id}:${s.id}`,m.id,i,s.title,JSON.stringify(s.acceptance),s.requiresApproval,s.status,s.attempts,s.startedAt??null,s.completedAt??null,s.lastError??null])}await c.query('COMMIT')}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
 async getMission(id:string){if(!this.enabled())return null;const r=await db().query('SELECT * FROM missions WHERE id=$1 AND instance_id=$2 AND ($3::text IS NULL OR workspace_id=$3)',[id,iid(),this.workspace()]);if(!r.rowCount)return null;const sr=await db().query('SELECT * FROM mission_steps WHERE mission_id=$1 ORDER BY ordinal',[id]);const x=r.rows[0];return {schemaVersion:'fs-remote.mission.v1',id:x.id,workspaceId:x.workspace_id??undefined,alias:x.alias??undefined,goal:x.goal,root:x.root,cwd:x.cwd,status:x.status,createdAt:new Date(x.created_at).toISOString(),updatedAt:new Date(x.updated_at).toISOString(),currentStepId:x.current_step_id??undefined,maxRemediationAttempts:x.max_remediation_attempts,metadata:x.metadata??{},steps:sr.rows.map((s:any)=>({id:String(s.id).split(':').slice(-1)[0],title:s.title,status:s.status,acceptance:s.acceptance??[],requiresApproval:s.requires_approval,attempts:s.attempts,startedAt:s.started_at?new Date(s.started_at).toISOString():undefined,completedAt:s.completed_at?new Date(s.completed_at).toISOString():undefined,lastError:s.last_error??undefined}))} as Mission}
 async listMissions(){if(!this.enabled())return null;const r=await db().query('SELECT id FROM missions WHERE instance_id=$1 AND ($2::text IS NULL OR workspace_id=$2) ORDER BY updated_at DESC',[iid(),this.workspace()]);return Promise.all(r.rows.map((x:any)=>this.getMission(x.id))) as Promise<Mission[]>}
 async addEvidence(e:Evidence){if(!this.enabled())return;await db().query(`INSERT INTO evidence(id,instance_id,mission_id,step_id,kind,source,status,summary,payload,observed_at,workspace_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(id) DO NOTHING`,[e.id,iid(),e.missionId,e.stepId??null,e.kind,e.source,e.status,e.summary,e.data??null,e.observedAt,this.workspace()])}
 async evidence(missionId:string){if(!this.enabled())return null;const r=await db().query('SELECT * FROM evidence WHERE instance_id=$1 AND mission_id=$2 AND ($3::text IS NULL OR workspace_id=$3) ORDER BY observed_at,id',[iid(),missionId,this.workspace()]);return r.rows.map((x:any)=>({schemaVersion:'fs-remote.evidence.v1',id:x.id,workspaceId:x.workspace_id??undefined,missionId:x.mission_id,stepId:x.step_id??undefined,kind:x.kind,source:x.source,status:x.status,summary:x.summary,observedAt:new Date(x.observed_at).toISOString(),data:x.payload??undefined})) as Evidence[]}
 async saveWork(w:WorkItem){if(!this.enabled())return;await db().query(`INSERT INTO work_items(id,instance_id,mission_id,step_id,kind,status,payload,attempts,max_attempts,available_at,lease_owner,lease_expires_at,error,result,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,now(),$10,$11,$12,$13,$14,$15) ON CONFLICT(id) DO UPDATE SET status=EXCLUDED.status,payload=EXCLUDED.payload,attempts=EXCLUDED.attempts,max_attempts=EXCLUDED.max_attempts,lease_owner=EXCLUDED.lease_owner,lease_expires_at=EXCLUDED.lease_expires_at,error=EXCLUDED.error,result=EXCLUDED.result,updated_at=EXCLUDED.updated_at`,[w.id,iid(),w.missionId,w.stepId,w.kind,w.status,w.payload,w.attempts,w.maxAttempts,w.lease?.workerId??null,w.lease?.expiresAt??null,w.error??null,w.result??null,w.createdAt,w.updatedAt])}
 async getWork(id:string){if(!this.enabled())return null;const r=await db().query('SELECT * FROM work_items WHERE id=$1 AND instance_id=$2',[id,iid()]);if(!r.rowCount)return null;return this.workRow(r.rows[0])}
 private workRow(x:any):WorkItem{return {schemaVersion:'fs-remote.work-item.v1',id:x.id,missionId:x.mission_id,stepId:x.step_id,kind:x.kind,payload:x.payload??{},status:x.status,createdAt:new Date(x.created_at).toISOString(),updatedAt:new Date(x.updated_at).toISOString(),attempts:x.attempts,maxAttempts:x.max_attempts,lease:x.lease_owner?{workerId:x.lease_owner,token:String((x.payload??{}).__leaseToken??''),leasedAt:new Date(x.updated_at).toISOString(),heartbeatAt:new Date(x.updated_at).toISOString(),expiresAt:new Date(x.lease_expires_at).toISOString()}:undefined,result:x.result??undefined,error:x.error??undefined}}
 async listWork(){if(!this.enabled())return null;const r=await db().query('SELECT * FROM work_items WHERE instance_id=$1 ORDER BY created_at',[iid()]);return r.rows.map((x:any)=>this.workRow(x))}
 async claim(workerId:string,kinds:string[],leaseMs:number){if(!this.enabled())return undefined;const token=crypto.randomBytes(24).toString('hex'),c=await db().connect();try{await c.query('BEGIN');const r=await c.query(`SELECT * FROM work_items WHERE instance_id=$1 AND status='queued' AND available_at<=now() AND ($2::text[]='{}' OR kind=ANY($2)) ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1`,[iid(),kinds]);if(!r.rowCount){await c.query('COMMIT');return null}const x=r.rows[0],payload={...(x.payload??{}),__leaseToken:token};const u=await c.query(`UPDATE work_items SET status='leased',attempts=attempts+1,lease_owner=$2,lease_expires_at=now()+($3::text||' milliseconds')::interval,payload=$4,updated_at=now() WHERE id=$1 RETURNING *`,[x.id,workerId,leaseMs,payload]);await c.query('COMMIT');return this.workRow(u.rows[0])}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
 async saveHandoff(h:MissionHandoff){if(!this.enabled())return;await db().query('INSERT INTO handoffs(id,instance_id,mission_id,alias,body,created_at) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(id) DO NOTHING',[h.id,iid(),h.missionId,h.alias??null,h,h.createdAt])}
 async handoffs(missionId:string){if(!this.enabled())return null;const r=await db().query('SELECT body FROM handoffs WHERE instance_id=$1 AND mission_id=$2 ORDER BY created_at DESC',[iid(),missionId]);return r.rows.map((x:any)=>x.body as MissionHandoff)}
}