import fs from 'node:fs/promises';
import path from 'node:path';
import type {ReviewerModel,BenchmarkRating} from './reviewer-broker.js';
import {benchmarkFeedHealth,normalizeBenchmarkSnapshots} from './benchmark-normalization.js';
import {discoverOpenRouterBenchmarks} from './openrouter-benchmarks.js';
export interface BenchmarkSnapshot{modelId:string;provider:'openrouter'|'nvidia'|'openai';ratings:BenchmarkRating[];observedAt:string;source:string}
const zero=(x:unknown)=>(typeof x==='number'||typeof x==='string'&&x.trim()!=='')&&Number.isFinite(Number(x))&&Number(x)===0;
const freePricing=(p:any)=>!!p&&zero(p.prompt)&&zero(p.completion)&&Object.values(p).every(zero);
export async function discoverOpenRouterModels():Promise<ReviewerModel[]>{const r=await fetch('https://openrouter.ai/api/v1/models',{signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error(`OpenRouter catalog ${r.status}`);const body:any=await r.json();return (body.data??[]).map((m:any)=>({id:String(m.id),canonicalId:typeof m.canonical_slug==='string'?m.canonical_slug:undefined,provider:'openrouter' as const,free:freePricing(m.pricing),coding:0,reasoning:0,security:0,context:Number(m.context_length??0),healthy:true,observedAt:new Date().toISOString(),source:'openrouter:/api/v1/models',benchmarks:[]}))}
export async function discoverOpenAIModels():Promise<ReviewerModel[]>{const key=process.env.OPENAI_API_KEY;if(!key)return [];const r=await fetch('https://api.openai.com/v1/models',{headers:{Authorization:`Bearer ${key}`},signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error(`OpenAI catalog ${r.status}`);const body:any=await r.json();return (body.data??[]).map((m:any)=>({id:String(m.id),provider:'openai' as const,free:false,coding:0,reasoning:0,security:0,context:0,healthy:true,observedAt:new Date().toISOString(),source:'openai:/v1/models',benchmarks:[]}))}
export async function discoverNvidiaModels():Promise<ReviewerModel[]>{const key=process.env.NVIDIA_API_KEY;if(!key)return [];const r=await fetch('https://integrate.api.nvidia.com/v1/models',{headers:{Authorization:`Bearer ${key}`},signal:AbortSignal.timeout(10000)});if(!r.ok)return [];const body:any=await r.json();const devFree=process.env.FS_REMOTE_NVIDIA_DEV_FREE==='true';return (body.data??[]).map((m:any)=>({id:String(m.id),provider:'nvidia' as const,free:freePricing(m.pricing)||(devFree&&(m.pricing===undefined||m.pricing===null)),coding:0,reasoning:0,security:0,context:Number(m.context_length??0),healthy:true,observedAt:new Date().toISOString(),source:'nvidia:/v1/models',benchmarks:[]}))}
export function mergeBenchmarks(models:ReviewerModel[],snapshots:BenchmarkSnapshot[]){const map=new Map(models.map(m=>[`${m.provider}:${m.id}`,{...m,benchmarks:[...(m.benchmarks??[])]}]));for(const s of snapshots){const key=`${s.provider}:${s.modelId}`,m=map.get(key);if(!m)continue;m.benchmarks=[...(m.benchmarks??[]),...s.ratings.map(r=>({...r,observedAt:r.observedAt||s.observedAt,source:r.source||s.source}))];map.set(key,m)}return [...map.values()]}
export async function discoverReviewerModels(){const results=await Promise.allSettled([discoverOpenRouterModels(),discoverNvidiaModels(),discoverOpenAIModels()]);return results.flatMap(r=>r.status==='fulfilled'?r.value:[])}
export async function loadBenchmarkSnapshots():Promise<BenchmarkSnapshot[]>{const inline=process.env.FS_REMOTE_REVIEWER_BENCHMARKS_JSON;if(inline!==undefined){const data=JSON.parse(inline);return normalizeBenchmarkSnapshots(Array.isArray(data)?data:data?.snapshots)}const url=process.env.FS_REMOTE_REVIEWER_BENCHMARKS_URL;if(url){const r=await fetch(url,{headers:process.env.FS_REMOTE_REVIEWER_BENCHMARKS_BEARER?{Authorization:`Bearer ${process.env.FS_REMOTE_REVIEWER_BENCHMARKS_BEARER}`}:{},signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error(`Benchmark snapshot source ${r.status}`);const data:any=await r.json();return normalizeBenchmarkSnapshots(Array.isArray(data)?data:data?.snapshots)}try{const local=JSON.parse(await fs.readFile(path.resolve('config/reviewer-benchmarks.seed.json'),'utf8'));return normalizeBenchmarkSnapshots(Array.isArray(local)?local:local?.snapshots)}catch(error){if((error as any)?.code==='ENOENT')return [];throw new Error('Configured local benchmark source is unavailable or malformed.')}}
async function benchmarkSourceConfigured(){if(process.env.FS_REMOTE_REVIEWER_BENCHMARKS_JSON!==undefined||process.env.FS_REMOTE_REVIEWER_BENCHMARKS_URL!==undefined)return true;try{await fs.access(path.resolve('config/reviewer-benchmarks.seed.json'));return true}catch(error){if((error as any)?.code==='ENOENT')return false;throw new Error('Configured local benchmark source cannot be inspected.')}}
export async function refreshReviewerCatalog(){const models=await discoverReviewerModels(),explicitSource=await benchmarkSourceConfigured();let snapshots=await loadBenchmarkSnapshots(),automaticBenchmarkSnapshots=0;if(!explicitSource&&!snapshots.length){try{const automatic=await discoverOpenRouterBenchmarks(models);snapshots=normalizeBenchmarkSnapshots(automatic);automaticBenchmarkSnapshots=snapshots.length}catch{}}const benchmarkHealth=benchmarkFeedHealth(snapshots);return {models:mergeBenchmarks(models,snapshots),sources:{models:models.length,benchmarkSnapshots:snapshots.length,automaticBenchmarkSnapshots,benchmarkHealth},observedAt:new Date().toISOString()}}
