export type ReviewerProvider='openrouter'|'nvidia'|'openai';
export type BenchmarkDimension='coding'|'reasoning'|'security'|'toolUse'|'longContext';
export interface BenchmarkRating{benchmark:string;dimension:BenchmarkDimension;score:number;observedAt:string;source:string;sampleSize?:number}
export interface ReviewerModel{id:string;provider:ReviewerProvider;free:boolean;coding:number;reasoning:number;security:number;context:number;healthy:boolean;observedAt:string;source:string;benchmarks?:BenchmarkRating[];usageRank?:number}
export interface ReviewerFleet{models:ReviewerModel[];assignments?:{role:string;modelId:string;provider:ReviewerProvider;benchmarkScore:number;benchmarks:string[]}[];autoSelected:boolean;notification?:string;reason:string}
const DAY=86400000;
const dims=(role:string):Record<BenchmarkDimension,number>=>/security|hardening/.test(role)?{coding:.15,reasoning:.2,security:.5,toolUse:.1,longContext:.05}:/testing|correctness|flutter|mobile|ux/.test(role)?{coding:.5,reasoning:.2,security:.05,toolUse:.15,longContext:.1}:/requirements|architecture|adjudicat/.test(role)?{coding:.15,reasoning:.5,security:.1,toolUse:.1,longContext:.15}:{coding:.4,reasoning:.3,security:.1,toolUse:.1,longContext:.1};
function benchmarkScore(m:ReviewerModel,role:string,maxAgeDays=90){const cutoff=Date.now()-maxAgeDays*DAY,weights=dims(role),ratings=(m.benchmarks??[]).filter(b=>Date.parse(b.observedAt)>=cutoff&&Number.isFinite(b.score));let total=0,weight=0;const used:string[]=[];for(const [dimension,w] of Object.entries(weights) as [BenchmarkDimension,number][]){const xs=ratings.filter(r=>r.dimension===dimension);if(!xs.length)continue;const best=Math.max(...xs.map(x=>x.score));total+=best*w;weight+=w;used.push(...xs.filter(x=>x.score===best).map(x=>`${x.benchmark}@${x.source}`))}return {score:weight?total/weight:-1,coverage:weight,used:[...new Set(used)]}}
export function selectReviewerFleet(catalog:ReviewerModel[],roles:string[],configuredIds:string[]=[]):ReviewerFleet{const healthy=catalog.filter(m=>m.healthy),configured=configuredIds.map(id=>healthy.find(m=>m.id===id)).filter(Boolean) as ReviewerModel[];if(configured.length)return {models:configured,autoSelected:false,reason:'Using user-configured healthy reviewer models.'};const free=healthy.filter(m=>m.free),pool=free.length?free:healthy,chosen:ReviewerModel[]=[],assignments:NonNullable<ReviewerFleet['assignments']>=[];for(const role of roles){const ranked=pool.map(m=>({m,b:benchmarkScore(m,role)})).filter(x=>x.b.score>=0&&x.b.coverage>=.4).sort((a,b)=>b.b.score-a.b.score||(a.m.usageRank??999999)-(b.m.usageRank??999999));const pick=ranked.find(x=>!chosen.some(c=>c.id===x.m.id))??ranked[0];if(!pick)continue;chosen.push(pick.m);assignments.push({role,modelId:pick.m.id,provider:pick.m.provider,benchmarkScore:pick.b.score,benchmarks:pick.b.used})}return {models:chosen,assignments,autoSelected:true,notification:'No reviewer fleet was configured when the project started. V3 selected task-specific reviewer models from fresh benchmark evidence; you can override the fleet at any time.',reason:chosen.length?(free.length?'Auto-selected currently healthy free models using fresh task-relevant benchmark ratings.':'No healthy free benchmarked models were available; selected benchmarked healthy provider models.'):'No healthy model had sufficient fresh task-relevant benchmark coverage; refresh provider/benchmark catalogs before review.'}}
export function reviewerCatalogNeedsRefresh(catalog:ReviewerModel[],maxAgeMs=6*60*60*1000){const fresh=catalog.filter(m=>m.healthy&&Date.now()-Date.parse(m.observedAt)<=maxAgeMs&&(m.benchmarks??[]).some(b=>Date.now()-Date.parse(b.observedAt)<=90*86400000));return fresh.length===0}
