import fs from 'node:fs/promises';
import path from 'node:path';
import type {ReviewerModel,BenchmarkRating} from './reviewer-broker.js';
export interface BenchmarkSnapshot{modelId:string;provider:'openrouter'|'nvidia'|'openai';ratings:BenchmarkRating[];observedAt:string;source:string}
const zero=(x:unknown)=>Number(x)===0||String(x)==='0';
export async function discoverOpenRouterModels():Promise<ReviewerModel[]>{const r=await fetch('https://openrouter.ai/api/v1/models');if(!r.ok)throw new Error(`OpenRouter catalog ${r.status}`);const body:any=await r.json();return (body.data??[]).map((m:any)=>({id:String(m.id),provider:'openrouter' as const,free:zero(m.pricing?.prompt)&&zero(m.pricing?.completion),coding:0,reasoning:0,security:0,context:Number(m.context_length??0),healthy:true,observedAt:new Date().toISOString(),source:'openrouter:/api/v1/models',benchmarks:[]}))}
export async function discoverOpenAIModels():Promise<ReviewerModel[]>{const key=process.env.OPENAI_API_KEY;if(!key)return [];const r=await fetch('https://api.openai.com/v1/models',{headers:{Authorization:`Bearer ${key}`}});if(!r.ok)throw new Error(`OpenAI catalog ${r.status}`);const body:any=await r.json();return (body.data??[]).map((m:any)=>({id:String(m.id),provider:'openai' as const,free:false,coding:0,reasoning:0,security:0,context:0,healthy:true,observedAt:new Date().toISOString(),source:'openai:/v1/models',benchmarks:[]}))}
export async function discoverNvidiaModels():Promise<ReviewerModel[]>{const key=process.env.NVIDIA_API_KEY;if(!key)return [];const r=await fetch('https://integrate.api.nvidia.com/v1/models',{headers:{Authorization:`Bearer ${key}`}});if(!r.ok)return [];const body:any=await r.json();const devFree=process.env.FS_REMOTE_NVIDIA_DEV_FREE==='true';return (body.data??[]).map((m:any)=>({id:String(m.id),provider:'nvidia' as const,free:devFree,coding:0,reasoning:0,security:0,context:Number(m.context_length??0),healthy:true,observedAt:new Date().toISOString(),source:'nvidia:/v1/models',benchmarks:[]}))}
export function mergeBenchmarks(models:ReviewerModel[],snapshots:BenchmarkSnapshot[]){const map=new Map(models.map(m=>[`${m.provider}:${m.id}`,{...m,benchmarks:[...(m.benchmarks??[])]}]));for(const s of snapshots){const key=`${s.provider}:${s.modelId}`,m=map.get(key);if(!m)continue;m.benchmarks=[...(m.benchmarks??[]),...s.ratings.map(r=>({...r,observedAt:r.observedAt||s.observedAt,source:r.source||s.source}))];map.set(key,m)}return [...map.values()]}
export async function discoverReviewerModels(){const results=await Promise.allSettled([discoverOpenRouterModels(),discoverNvidiaModels(),discoverOpenAIModels()]);return results.flatMap(r=>r.status==='fulfilled'?r.value:[])}
export async function loadBenchmarkSnapshots():Promise<BenchmarkSnapshot[]>{const inline=process.env.FS_REMOTE_REVIEWER_BENCHMARKS_JSON;if(inline){const data=JSON.parse(inline);return Array.isArray(data)?data:[]}const url=process.env.FS_REMOTE_REVIEWER_BENCHMARKS_URL;if(url){const r=await fetch(url,{headers:process.env.FS_REMOTE_REVIEWER_BENCHMARKS_BEARER?{Authorization:`Bearer ${process.env.FS_REMOTE_REVIEWER_BENCHMARKS_BEARER}`}:{}});if(!r.ok)throw new Error(`Benchmark snapshot source ${r.status}`);const data:any=await r.json();return Array.isArray(data)?data:Array.isArray(data.snapshots)?data.snapshots:[]}try{const local=JSON.parse(await fs.readFile(path.resolve('config/reviewer-benchmarks.seed.json'),'utf8'));return Array.isArray(local)?local:Array.isArray(local.snapshots)?local.snapshots:[]}catch{return []}}
export async function refreshReviewerCatalog(){const models=await discoverReviewerModels(),snapshots=await loadBenchmarkSnapshots();return {models:mergeBenchmarks(models,snapshots),sources:{models:models.length,benchmarkSnapshots:snapshots.length},observedAt:new Date().toISOString()}}
