import crypto from 'node:crypto';
export type ExecutionTarget='local'|'sandbox'|'hosted';
export interface SandboxProviderStatus{provider:'opensandbox';enabled:boolean;configured:boolean;healthy:boolean;endpoint?:string;reason?:string}
export interface SandboxPolicy{image?:string;ttlSeconds?:number;cpu?:number;memoryMb?:number;network?:'none'|'restricted'|'full';allowCredentials?:boolean;materialization?:{kind:'git';repository:string;revision:string;subdir?:string}|{kind:'files';files:Array<{path:string;content:string}>}}
export interface SandboxJob{missionId:string;stepId:string;capability:string;operation:string;payload:Record<string,unknown>;policy:SandboxPolicy}
export class OpenSandboxProvider{
 private endpoint=(process.env.FS_OPENSANDBOX_URL??'').replace(/\/$/,''); private key=process.env.FS_OPENSANDBOX_API_KEY??'';
 configured(){return !!this.endpoint} private headers(){return{'content-type':'application/json',...(this.key?{'authorization':`Bearer ${this.key}`}:{})}}
 async status():Promise<SandboxProviderStatus>{if(!this.endpoint)return{provider:'opensandbox',enabled:false,configured:false,healthy:false,reason:'FS_OPENSANDBOX_URL is not configured.'};try{const r=await fetch(this.endpoint+'/health',{headers:this.headers(),signal:AbortSignal.timeout(5000)});return{provider:'opensandbox',enabled:true,configured:true,healthy:r.ok,endpoint:this.endpoint,reason:r.ok?undefined:`Health HTTP ${r.status}`}}catch(e){return{provider:'opensandbox',enabled:true,configured:true,healthy:false,endpoint:this.endpoint,reason:e instanceof Error?e.message:String(e)}}}
 capabilities(){return{provider:'opensandbox',configured:this.configured(),defaultTarget:'local' as const,supportedTargets:['local','sandbox','hosted'] as ExecutionTarget[],policy:'Sandbox is opt-in. Materialization, network, resources and credentials must be explicit.'}}
 validate(job:SandboxJob){const p=job.policy;if(!p.materialization)throw new Error('Sandbox materialization policy is required.');if((p.ttlSeconds??1800)>7200)throw new Error('Sandbox TTL exceeds 7200 seconds.');if((p.memoryMb??2048)>16384)throw new Error('Sandbox memory exceeds 16384 MB.');if((p.cpu??2)>8)throw new Error('Sandbox CPU exceeds 8 cores.');if(p.allowCredentials&&!this.key)throw new Error('Sandbox credentials were requested but no provider credential is configured.');if(p.materialization.kind==='files'){if(p.materialization.files.length>500)throw new Error('Sandbox file materialization exceeds 500 files.');const bytes=p.materialization.files.reduce((n,f)=>n+Buffer.byteLength(f.content),0);if(bytes>20*1024*1024)throw new Error('Sandbox file materialization exceeds 20 MB.');for(const f of p.materialization.files)if(!f.path||f.path.includes('..')||f.path.startsWith('/')||/^[A-Za-z]:/.test(f.path))throw new Error(`Unsafe sandbox materialization path: ${f.path}`);}if(p.materialization.kind==='git'&&(!/^https:\/\//.test(p.materialization.repository)||!p.materialization.revision))throw new Error('Sandbox git materialization requires an HTTPS repository and immutable revision/ref.');return{...p,ttlSeconds:p.ttlSeconds??1800,cpu:p.cpu??2,memoryMb:p.memoryMb??2048,network:p.network??'restricted',allowCredentials:p.allowCredentials??false}}
 async execute(job:SandboxJob){if(!this.endpoint)throw new Error('OpenSandbox is not configured.');const policy=this.validate(job),requestId=`sandbox-${Date.now()}-${crypto.randomBytes(3).toString('hex')}`;const r=await fetch(this.endpoint+'/api/fs-remote/v1/jobs',{method:'POST',headers:this.headers(),body:JSON.stringify({requestId,missionId:job.missionId,stepId:job.stepId,capability:job.capability,operation:job.operation,payload:job.payload,policy}),signal:AbortSignal.timeout(30000)});if(!r.ok)throw new Error(`OpenSandbox job submission HTTP ${r.status}: ${(await r.text()).slice(0,1000)}`);const result:any=await r.json();return{schemaVersion:'fs-remote.sandbox-result.v1',requestId,provider:'opensandbox',status:String(result.status??'submitted'),sandboxId:result.sandboxId??null,jobId:result.jobId??null,result:result.result??null,evidence:result.evidence??null,policy:{ttlSeconds:policy.ttlSeconds,cpu:policy.cpu,memoryMb:policy.memoryMb,network:policy.network,allowCredentials:policy.allowCredentials}}}
}
