import crypto from 'node:crypto';import type {FastifyInstance,FastifyReply,FastifyRequest} from 'fastify';import {AuthStore,type AuthPrincipal} from './auth-store.js';import {ProviderUserStore} from './provider-user-store.js';import {NodeRegistry} from './nodes.js';import {db} from './db.js';import {hashOpaqueToken,issueOpaqueToken} from './auth-crypto.js';
const bearer=(r:FastifyRequest)=>r.headers.authorization?.startsWith('Bearer ')?r.headers.authorization.slice(7).trim():'';async function principal(r:FastifyRequest,reply:FastifyReply,store:AuthStore){const p=await store.resolve(bearer(r));if(!p?.workspaceId){await reply.code(401).send({error:'Unauthorized.'});return null}return p}
export function registerUserPlatformRoutes(app:FastifyInstance){const auth=new AuthStore(),models=new ProviderUserStore();
 app.get('/api/account/models',async(r,reply)=>{const p=await principal(r,reply,auth);if(!p)return;return {preferences:await models.preferences(p.workspaceId!,p.userId)}});
 app.put('/api/account/models/:purpose',async(r:any,reply)=>{const p=await principal(r,reply,auth);if(!p)return;try{const b=r.body??{};return await models.set({workspaceId:p.workspaceId!,userId:p.userId,provider:String(b.provider??''),modelId:b.modelId?String(b.modelId):undefined,purpose:r.params.purpose,costPolicy:b.costPolicy??'free_first',paidConsent:b.paidConsent===true})}catch(e){return reply.code(400).send({error:e instanceof Error?e.message:'Invalid model preference.'})}});
 app.post('/api/account/nodes/enroll',async(r:any,reply)=>{const p=await principal(r,reply,auth);if(!p)return;if(!['owner','admin','engineer'].includes(String(p.role)))return reply.code(403).send({error:'Role cannot enroll execution nodes.'});const b=r.body??{},token=issueOpaqueToken(),id=`enroll-${crypto.randomUUID()}`,expiresAt=new Date(Date.now()+15*60_000);await db().query(`INSERT INTO node_enrollments(id,workspace_id,user_id,token_hash,name,platform,projects,capabilities,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[id,p.workspaceId,p.userId,hashOpaqueToken(token),String(b.name??'My computer'),String(b.platform??'win32'),JSON.stringify(Array.isArray(b.projects)?b.projects:[]),JSON.stringify(Array.isArray(b.capabilities)?b.capabilities:['filesystem','command','git']),expiresAt]);return reply.code(201).send({enrollmentId:id,token,expiresAt:expiresAt.toISOString()})});
 app.post('/api/nodes/enrollment/consume',async(r:any,reply)=>{const c=await db().connect();try{await c.query('BEGIN');const x=(await c.query(`SELECT * FROM node_enrollments WHERE token_hash=$1 AND consumed_at IS NULL AND expires_at>now() FOR UPDATE`,[hashOpaqueToken(String(r.body?.token??''))])).rows[0];if(!x)throw new Error('Enrollment is invalid, expired, or consumed.');const nodeId=String(r.body?.nodeId??`node-${crypto.randomUUID()}`);const reg=new NodeRegistry(x.workspace_id);const out=await reg.register({nodeId,name:x.name,platform:x.platform,capabilities:x.capabilities,projects:x.projects,metadata:{ownerUserId:x.user_id}});await c.query(`UPDATE node_enrollments SET consumed_at=now() WHERE id=$1`,[x.id]);await c.query('COMMIT');return reply.code(201).send({...out,nodeId,workspaceId:x.workspace_id})}catch(e){await c.query('ROLLBACK');return reply.code(400).send({error:e instanceof Error?e.message:'Enrollment failed.'})}finally{c.release()}});
 app.get('/api/account/nodes',async(r,reply)=>{const p=await principal(r,reply,auth);if(!p)return;return {nodes:await new NodeRegistry(p.workspaceId!).list()}});
 app.get('/api/account/gpt',async(r,reply)=>{const p=await principal(r,reply,auth);if(!p)return;const rows=(await db().query(`SELECT id,client_id,scopes,status,created_at,revoked_at FROM oauth_connections WHERE workspace_id=$1 AND user_id=$2 ORDER BY created_at DESC`,[p.workspaceId,p.userId])).rows;return {connections:rows,actionBaseUrl:`${String(process.env.FS_PUBLIC_BASE_URL??'').replace(/\/$/,'')}/actions`,authMode:'OAuth'}});
 app.post('/api/account/gpt/connect',async(r:any,reply)=>{const p=await principal(r,reply,auth);if(!p)return;const clientId=String(r.body?.clientId??'chatgpt-custom-gpt'),scopes=['fs.read','fs.write','fs.node','fs.models'].filter(x=>p.role==='viewer'||p.role==='reviewer'?x==='fs.read':true),id=`gpt-${crypto.randomUUID()}`;await db().query(`INSERT INTO oauth_connections(id,workspace_id,user_id,client_id,scopes,status) VALUES($1,$2,$3,$4,$5,'active') ON CONFLICT(workspace_id,user_id,client_id) DO UPDATE SET scopes=excluded.scopes,status='active',revoked_at=NULL`,[id,p.workspaceId,p.userId,clientId,JSON.stringify(scopes)]);return reply.code(201).send({connected:true,clientId,scopes})});
 app.delete('/api/account/gpt/:clientId',async(r:any,reply)=>{const p=await principal(r,reply,auth);if(!p)return;await db().query(`UPDATE oauth_connections SET status='revoked',revoked_at=now() WHERE workspace_id=$1 AND user_id=$2 AND client_id=$3`,[p.workspaceId,p.userId,r.params.clientId]);return {revoked:true}});
}
