import fs from 'node:fs/promises';import path from 'node:path';import crypto from 'node:crypto';
export type WorkStatus='queued'|'leased'|'completed'|'failed'|'cancelled';
export interface WorkItem{schemaVersion:'fs-remote.work-item.v1';id:string;missionId:string;stepId:string;kind:string;payload:Record<string,unknown>;status:WorkStatus;createdAt:string;updatedAt:string;attempts:number;maxAttempts:number;lease?:{workerId:string;token:string;leasedAt:string;heartbeatAt:string;expiresAt:string};result?:Record<string,unknown>;error?:string}
export class WorkerQueue{
 constructor(private readonly base:string,private readonly defaultLeaseMs=120000){}
 private file(id:string){if(!/^[A-Za-z0-9._-]+$/.test(id))throw new Error('Invalid work item id.');return path.join(this.base,`${id}.json`)}
 private async save(w:WorkItem){w.updatedAt=new Date().toISOString();await fs.mkdir(this.base,{recursive:true});await fs.writeFile(this.file(w.id),JSON.stringify(w,null,2),'utf8');return w}
 async enqueue(input:{missionId:string;stepId:string;kind:string;payload?:Record<string,unknown>;maxAttempts?:number}){const now=new Date().toISOString();const w:WorkItem={schemaVersion:'fs-remote.work-item.v1',id:`work-${Date.now()}-${crypto.randomBytes(3).toString('hex')}`,missionId:input.missionId,stepId:input.stepId,kind:input.kind,payload:input.payload??{},status:'queued',createdAt:now,updatedAt:now,attempts:0,maxAttempts:input.maxAttempts??3};return this.save(w)}
 async get(id:string){return JSON.parse(await fs.readFile(this.file(id),'utf8')) as WorkItem}
 async list(){try{const names=(await fs.readdir(this.base)).filter(x=>x.endsWith('.json'));const out=[];for(const n of names)try{out.push(await this.get(n.slice(0,-5)))}catch{}return out.sort((a,b)=>a.createdAt.localeCompare(b.createdAt))}catch{return []}}
 async recover(){const now=Date.now(),items=await this.list();let recovered=0,failed=0;for(const w of items){if(w.status!=='leased'||!w.lease||Date.parse(w.lease.expiresAt)>now)continue;w.lease=undefined;if(w.attempts>=w.maxAttempts){w.status='failed';w.error='Worker lease expired and retry budget exhausted.';failed++}else{w.status='queued';w.error='Previous worker lease expired; item recovered for retry.';recovered++}await this.save(w)}return {recovered,failed}}
 async claim(workerId:string,kinds:string[]=[],leaseMs=this.defaultLeaseMs){if(!/^[A-Za-z0-9._-]+$/.test(workerId))throw new Error('Invalid workerId.');await this.recover();const items=await this.list();const w=items.find(x=>x.status==='queued'&&(!kinds.length||kinds.includes(x.kind)));if(!w)return null;const now=new Date(),token=crypto.randomBytes(24).toString('hex');w.status='leased';w.attempts++;w.lease={workerId,token,leasedAt:now.toISOString(),heartbeatAt:now.toISOString(),expiresAt:new Date(now.getTime()+leaseMs).toISOString()};return this.save(w)}
 private async owned(id:string,workerId:string,token:string){const w=await this.get(id);if(w.status!=='leased'||!w.lease||w.lease.workerId!==workerId||w.lease.token!==token)throw new Error('Work item lease is not owned by this worker.');if(Date.parse(w.lease.expiresAt)<Date.now())throw new Error('Work item lease has expired.');return w}
 async heartbeat(id:string,workerId:string,token:string,leaseMs=this.defaultLeaseMs){const w=await this.owned(id,workerId,token),now=new Date();w.lease!.heartbeatAt=now.toISOString();w.lease!.expiresAt=new Date(now.getTime()+leaseMs).toISOString();return this.save(w)}
 async complete(id:string,workerId:string,token:string,result:Record<string,unknown>={}){const w=await this.owned(id,workerId,token);w.status='completed';w.result=result;w.lease=undefined;w.error=undefined;return this.save(w)}
 async fail(id:string,workerId:string,token:string,error:string,retry=true){const w=await this.owned(id,workerId,token);w.lease=undefined;w.error=error;if(retry&&w.attempts<w.maxAttempts)w.status='queued';else w.status='failed';return this.save(w)}
 async cancel(id:string){const w=await this.get(id);if(w.status==='completed')throw new Error('Completed work cannot be cancelled.');w.status='cancelled';w.lease=undefined;return this.save(w)}
 async status(){const items=await this.list();return {total:items.length,queued:items.filter(x=>x.status==='queued').length,leased:items.filter(x=>x.status==='leased').length,completed:items.filter(x=>x.status==='completed').length,failed:items.filter(x=>x.status==='failed').length,cancelled:items.filter(x=>x.status==='cancelled').length};}
}
